package com.goochou.p2b.model;

import java.util.Date;

public class ActivityCouponRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_coupon_record.id
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_coupon_record.gift_id
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    private Integer giftId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_coupon_record.type
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_coupon_record.rate
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    private Double rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_coupon_record.phone
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_coupon_record.create_time
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_coupon_record.over_time
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    private Date overTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_coupon_record.status
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_coupon_record.id
     *
     * @return the value of activity_coupon_record.id
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_coupon_record.id
     *
     * @param id the value for activity_coupon_record.id
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_coupon_record.gift_id
     *
     * @return the value of activity_coupon_record.gift_id
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public Integer getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_coupon_record.gift_id
     *
     * @param giftId the value for activity_coupon_record.gift_id
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public void setGiftId(Integer giftId) {
        this.giftId = giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_coupon_record.type
     *
     * @return the value of activity_coupon_record.type
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_coupon_record.type
     *
     * @param type the value for activity_coupon_record.type
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_coupon_record.rate
     *
     * @return the value of activity_coupon_record.rate
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_coupon_record.rate
     *
     * @param rate the value for activity_coupon_record.rate
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_coupon_record.phone
     *
     * @return the value of activity_coupon_record.phone
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_coupon_record.phone
     *
     * @param phone the value for activity_coupon_record.phone
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_coupon_record.create_time
     *
     * @return the value of activity_coupon_record.create_time
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_coupon_record.create_time
     *
     * @param createTime the value for activity_coupon_record.create_time
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_coupon_record.over_time
     *
     * @return the value of activity_coupon_record.over_time
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public Date getOverTime() {
        return overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_coupon_record.over_time
     *
     * @param overTime the value for activity_coupon_record.over_time
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public void setOverTime(Date overTime) {
        this.overTime = overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_coupon_record.status
     *
     * @return the value of activity_coupon_record.status
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_coupon_record.status
     *
     * @param status the value for activity_coupon_record.status
     *
     * @mbggenerated Mon Dec 14 13:27:27 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}