package com.goochou.p2b.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class AppAsoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_aso
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_aso
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_aso
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_aso
	 * @mbg.generated
	 */
	public AppAsoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_aso
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_aso
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_aso
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_aso
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_aso
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_aso
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_aso
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_aso
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_aso
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_aso
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app_aso
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNull() {
			addCriterion("app_id is null");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("app_id is not null");
			return (Criteria) this;
		}

		public Criteria andAppIdEqualTo(Long value) {
			addCriterion("app_id =", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotEqualTo(Long value) {
			addCriterion("app_id <>", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThan(Long value) {
			addCriterion("app_id >", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(Long value) {
			addCriterion("app_id >=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThan(Long value) {
			addCriterion("app_id <", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThanOrEqualTo(Long value) {
			addCriterion("app_id <=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdIn(List<Long> values) {
			addCriterion("app_id in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotIn(List<Long> values) {
			addCriterion("app_id not in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdBetween(Long value1, Long value2) {
			addCriterion("app_id between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotBetween(Long value1, Long value2) {
			addCriterion("app_id not between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andUuidIsNull() {
			addCriterion("uuid is null");
			return (Criteria) this;
		}

		public Criteria andUuidIsNotNull() {
			addCriterion("uuid is not null");
			return (Criteria) this;
		}

		public Criteria andUuidEqualTo(String value) {
			addCriterion("uuid =", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotEqualTo(String value) {
			addCriterion("uuid <>", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidGreaterThan(String value) {
			addCriterion("uuid >", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidGreaterThanOrEqualTo(String value) {
			addCriterion("uuid >=", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLessThan(String value) {
			addCriterion("uuid <", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLessThanOrEqualTo(String value) {
			addCriterion("uuid <=", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidLike(String value) {
			addCriterion("uuid like", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotLike(String value) {
			addCriterion("uuid not like", value, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidIn(List<String> values) {
			addCriterion("uuid in", values, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotIn(List<String> values) {
			addCriterion("uuid not in", values, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidBetween(String value1, String value2) {
			addCriterion("uuid between", value1, value2, "uuid");
			return (Criteria) this;
		}

		public Criteria andUuidNotBetween(String value1, String value2) {
			addCriterion("uuid not between", value1, value2, "uuid");
			return (Criteria) this;
		}

		public Criteria andIdfaIsNull() {
			addCriterion("idfa is null");
			return (Criteria) this;
		}

		public Criteria andIdfaIsNotNull() {
			addCriterion("idfa is not null");
			return (Criteria) this;
		}

		public Criteria andIdfaEqualTo(String value) {
			addCriterion("idfa =", value, "idfa");
			return (Criteria) this;
		}

		public Criteria andIdfaNotEqualTo(String value) {
			addCriterion("idfa <>", value, "idfa");
			return (Criteria) this;
		}

		public Criteria andIdfaGreaterThan(String value) {
			addCriterion("idfa >", value, "idfa");
			return (Criteria) this;
		}

		public Criteria andIdfaGreaterThanOrEqualTo(String value) {
			addCriterion("idfa >=", value, "idfa");
			return (Criteria) this;
		}

		public Criteria andIdfaLessThan(String value) {
			addCriterion("idfa <", value, "idfa");
			return (Criteria) this;
		}

		public Criteria andIdfaLessThanOrEqualTo(String value) {
			addCriterion("idfa <=", value, "idfa");
			return (Criteria) this;
		}

		public Criteria andIdfaLike(String value) {
			addCriterion("idfa like", value, "idfa");
			return (Criteria) this;
		}

		public Criteria andIdfaNotLike(String value) {
			addCriterion("idfa not like", value, "idfa");
			return (Criteria) this;
		}

		public Criteria andIdfaIn(List<String> values) {
			addCriterion("idfa in", values, "idfa");
			return (Criteria) this;
		}

		public Criteria andIdfaNotIn(List<String> values) {
			addCriterion("idfa not in", values, "idfa");
			return (Criteria) this;
		}

		public Criteria andIdfaBetween(String value1, String value2) {
			addCriterion("idfa between", value1, value2, "idfa");
			return (Criteria) this;
		}

		public Criteria andIdfaNotBetween(String value1, String value2) {
			addCriterion("idfa not between", value1, value2, "idfa");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIsNull() {
			addCriterion("secret_key is null");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIsNotNull() {
			addCriterion("secret_key is not null");
			return (Criteria) this;
		}

		public Criteria andSecretKeyEqualTo(String value) {
			addCriterion("secret_key =", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotEqualTo(String value) {
			addCriterion("secret_key <>", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyGreaterThan(String value) {
			addCriterion("secret_key >", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyGreaterThanOrEqualTo(String value) {
			addCriterion("secret_key >=", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLessThan(String value) {
			addCriterion("secret_key <", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLessThanOrEqualTo(String value) {
			addCriterion("secret_key <=", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLike(String value) {
			addCriterion("secret_key like", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotLike(String value) {
			addCriterion("secret_key not like", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIn(List<String> values) {
			addCriterion("secret_key in", values, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotIn(List<String> values) {
			addCriterion("secret_key not in", values, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyBetween(String value1, String value2) {
			addCriterion("secret_key between", value1, value2, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotBetween(String value1, String value2) {
			addCriterion("secret_key not between", value1, value2, "secretKey");
			return (Criteria) this;
		}

		public Criteria andDeviceNameIsNull() {
			addCriterion("device_name is null");
			return (Criteria) this;
		}

		public Criteria andDeviceNameIsNotNull() {
			addCriterion("device_name is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceNameEqualTo(String value) {
			addCriterion("device_name =", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotEqualTo(String value) {
			addCriterion("device_name <>", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameGreaterThan(String value) {
			addCriterion("device_name >", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameGreaterThanOrEqualTo(String value) {
			addCriterion("device_name >=", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameLessThan(String value) {
			addCriterion("device_name <", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameLessThanOrEqualTo(String value) {
			addCriterion("device_name <=", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameLike(String value) {
			addCriterion("device_name like", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotLike(String value) {
			addCriterion("device_name not like", value, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameIn(List<String> values) {
			addCriterion("device_name in", values, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotIn(List<String> values) {
			addCriterion("device_name not in", values, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameBetween(String value1, String value2) {
			addCriterion("device_name between", value1, value2, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceNameNotBetween(String value1, String value2) {
			addCriterion("device_name not between", value1, value2, "deviceName");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionIsNull() {
			addCriterion("device_version is null");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionIsNotNull() {
			addCriterion("device_version is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionEqualTo(String value) {
			addCriterion("device_version =", value, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionNotEqualTo(String value) {
			addCriterion("device_version <>", value, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionGreaterThan(String value) {
			addCriterion("device_version >", value, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionGreaterThanOrEqualTo(String value) {
			addCriterion("device_version >=", value, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionLessThan(String value) {
			addCriterion("device_version <", value, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionLessThanOrEqualTo(String value) {
			addCriterion("device_version <=", value, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionLike(String value) {
			addCriterion("device_version like", value, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionNotLike(String value) {
			addCriterion("device_version not like", value, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionIn(List<String> values) {
			addCriterion("device_version in", values, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionNotIn(List<String> values) {
			addCriterion("device_version not in", values, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionBetween(String value1, String value2) {
			addCriterion("device_version between", value1, value2, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceVersionNotBetween(String value1, String value2) {
			addCriterion("device_version not between", value1, value2, "deviceVersion");
			return (Criteria) this;
		}

		public Criteria andDeviceMacIsNull() {
			addCriterion("device_mac is null");
			return (Criteria) this;
		}

		public Criteria andDeviceMacIsNotNull() {
			addCriterion("device_mac is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceMacEqualTo(String value) {
			addCriterion("device_mac =", value, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andDeviceMacNotEqualTo(String value) {
			addCriterion("device_mac <>", value, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andDeviceMacGreaterThan(String value) {
			addCriterion("device_mac >", value, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andDeviceMacGreaterThanOrEqualTo(String value) {
			addCriterion("device_mac >=", value, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andDeviceMacLessThan(String value) {
			addCriterion("device_mac <", value, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andDeviceMacLessThanOrEqualTo(String value) {
			addCriterion("device_mac <=", value, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andDeviceMacLike(String value) {
			addCriterion("device_mac like", value, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andDeviceMacNotLike(String value) {
			addCriterion("device_mac not like", value, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andDeviceMacIn(List<String> values) {
			addCriterion("device_mac in", values, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andDeviceMacNotIn(List<String> values) {
			addCriterion("device_mac not in", values, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andDeviceMacBetween(String value1, String value2) {
			addCriterion("device_mac between", value1, value2, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andDeviceMacNotBetween(String value1, String value2) {
			addCriterion("device_mac not between", value1, value2, "deviceMac");
			return (Criteria) this;
		}

		public Criteria andNetWorkIsNull() {
			addCriterion("net_work is null");
			return (Criteria) this;
		}

		public Criteria andNetWorkIsNotNull() {
			addCriterion("net_work is not null");
			return (Criteria) this;
		}

		public Criteria andNetWorkEqualTo(String value) {
			addCriterion("net_work =", value, "netWork");
			return (Criteria) this;
		}

		public Criteria andNetWorkNotEqualTo(String value) {
			addCriterion("net_work <>", value, "netWork");
			return (Criteria) this;
		}

		public Criteria andNetWorkGreaterThan(String value) {
			addCriterion("net_work >", value, "netWork");
			return (Criteria) this;
		}

		public Criteria andNetWorkGreaterThanOrEqualTo(String value) {
			addCriterion("net_work >=", value, "netWork");
			return (Criteria) this;
		}

		public Criteria andNetWorkLessThan(String value) {
			addCriterion("net_work <", value, "netWork");
			return (Criteria) this;
		}

		public Criteria andNetWorkLessThanOrEqualTo(String value) {
			addCriterion("net_work <=", value, "netWork");
			return (Criteria) this;
		}

		public Criteria andNetWorkLike(String value) {
			addCriterion("net_work like", value, "netWork");
			return (Criteria) this;
		}

		public Criteria andNetWorkNotLike(String value) {
			addCriterion("net_work not like", value, "netWork");
			return (Criteria) this;
		}

		public Criteria andNetWorkIn(List<String> values) {
			addCriterion("net_work in", values, "netWork");
			return (Criteria) this;
		}

		public Criteria andNetWorkNotIn(List<String> values) {
			addCriterion("net_work not in", values, "netWork");
			return (Criteria) this;
		}

		public Criteria andNetWorkBetween(String value1, String value2) {
			addCriterion("net_work between", value1, value2, "netWork");
			return (Criteria) this;
		}

		public Criteria andNetWorkNotBetween(String value1, String value2) {
			addCriterion("net_work not between", value1, value2, "netWork");
			return (Criteria) this;
		}

		public Criteria andIpIsNull() {
			addCriterion("ip is null");
			return (Criteria) this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("ip is not null");
			return (Criteria) this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("ip =", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("ip <>", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("ip >", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("ip >=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("ip <", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("ip <=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("ip like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("ip not like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("ip in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("ip not in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("ip between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("ip not between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("type like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("type not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andActiTimeIsNull() {
			addCriterion("acti_time is null");
			return (Criteria) this;
		}

		public Criteria andActiTimeIsNotNull() {
			addCriterion("acti_time is not null");
			return (Criteria) this;
		}

		public Criteria andActiTimeEqualTo(Date value) {
			addCriterion("acti_time =", value, "actiTime");
			return (Criteria) this;
		}

		public Criteria andActiTimeNotEqualTo(Date value) {
			addCriterion("acti_time <>", value, "actiTime");
			return (Criteria) this;
		}

		public Criteria andActiTimeGreaterThan(Date value) {
			addCriterion("acti_time >", value, "actiTime");
			return (Criteria) this;
		}

		public Criteria andActiTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("acti_time >=", value, "actiTime");
			return (Criteria) this;
		}

		public Criteria andActiTimeLessThan(Date value) {
			addCriterion("acti_time <", value, "actiTime");
			return (Criteria) this;
		}

		public Criteria andActiTimeLessThanOrEqualTo(Date value) {
			addCriterion("acti_time <=", value, "actiTime");
			return (Criteria) this;
		}

		public Criteria andActiTimeIn(List<Date> values) {
			addCriterion("acti_time in", values, "actiTime");
			return (Criteria) this;
		}

		public Criteria andActiTimeNotIn(List<Date> values) {
			addCriterion("acti_time not in", values, "actiTime");
			return (Criteria) this;
		}

		public Criteria andActiTimeBetween(Date value1, Date value2) {
			addCriterion("acti_time between", value1, value2, "actiTime");
			return (Criteria) this;
		}

		public Criteria andActiTimeNotBetween(Date value1, Date value2) {
			addCriterion("acti_time not between", value1, value2, "actiTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app_aso
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_aso
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}