package com.goochou.p2b.model;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;
import net.sf.json.JSONObject;
import com.goochou.p2b.utils.DateUtil;
import com.goochou.p2b.utils.MoneyUtil;

public class ContractFile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.idx
     *
     * @mbggenerated
     */
    private Long idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.landlord_id
     *
     * @mbggenerated
     */
    private Integer landlordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.landlord_name
     *
     * @mbggenerated
     */
    private String landlordName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.channel_user_id
     *
     * @mbggenerated
     */
    private String channelUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.contract_id
     *
     * @mbggenerated
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.data
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.show_status
     *
     * @mbggenerated
     */
    private String showStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.contract_download_url
     *
     * @mbggenerated
     */
    private String contractDownloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.contract_view_url
     *
     * @mbggenerated
     */
    private String contractViewUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.operate_id
     *
     * @mbggenerated
     */
    private String operateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.operate_name
     *
     * @mbggenerated
     */
    private String operateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_contract_file.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;
    
    /**
     * 
     */
    private String isCreatedProject;
    
    private Date lendBeginTime;
    
    private double totalAmount;
    
    private Integer lendMonth;
    
    private Integer lendCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_contract_file
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.idx
     *
     * @return the value of tc_contract_file.idx
     *
     * @mbggenerated
     */
    public Long getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.idx
     *
     * @param idx the value for tc_contract_file.idx
     *
     * @mbggenerated
     */
    public void setIdx(Long idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.id
     *
     * @return the value of tc_contract_file.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.id
     *
     * @param id the value for tc_contract_file.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.landlord_id
     *
     * @return the value of tc_contract_file.landlord_id
     *
     * @mbggenerated
     */
    public Integer getLandlordId() {
        return landlordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.landlord_id
     *
     * @param landlordId the value for tc_contract_file.landlord_id
     *
     * @mbggenerated
     */
    public void setLandlordId(Integer landlordId) {
        this.landlordId = landlordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.landlord_name
     *
     * @return the value of tc_contract_file.landlord_name
     *
     * @mbggenerated
     */
    public String getLandlordName() {
        return landlordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.landlord_name
     *
     * @param landlordName the value for tc_contract_file.landlord_name
     *
     * @mbggenerated
     */
    public void setLandlordName(String landlordName) {
        this.landlordName = landlordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.channel_user_id
     *
     * @return the value of tc_contract_file.channel_user_id
     *
     * @mbggenerated
     */
    public String getChannelUserId() {
        return channelUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.channel_user_id
     *
     * @param channelUserId the value for tc_contract_file.channel_user_id
     *
     * @mbggenerated
     */
    public void setChannelUserId(String channelUserId) {
        this.channelUserId = channelUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.contract_id
     *
     * @return the value of tc_contract_file.contract_id
     *
     * @mbggenerated
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.contract_id
     *
     * @param contractId the value for tc_contract_file.contract_id
     *
     * @mbggenerated
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.data
     *
     * @return the value of tc_contract_file.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }
    
    private Object getData(String param){
    	try {
			JSONObject object = JSONObject.fromObject(data);
			return object.get(param);
		} catch (Exception e) {
			e.printStackTrace();
		}
    	return "";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.data
     *
     * @param data the value for tc_contract_file.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.status
     *
     * @return the value of tc_contract_file.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.status
     *
     * @param status the value for tc_contract_file.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.show_status
     *
     * @return the value of tc_contract_file.show_status
     *
     * @mbggenerated
     */
    public String getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.show_status
     *
     * @param showStatus the value for tc_contract_file.show_status
     *
     * @mbggenerated
     */
    public void setShowStatus(String showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.contract_download_url
     *
     * @return the value of tc_contract_file.contract_download_url
     *
     * @mbggenerated
     */
    public String getContractDownloadUrl() {
        return contractDownloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.contract_download_url
     *
     * @param contractDownloadUrl the value for tc_contract_file.contract_download_url
     *
     * @mbggenerated
     */
    public void setContractDownloadUrl(String contractDownloadUrl) {
        this.contractDownloadUrl = contractDownloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.contract_view_url
     *
     * @return the value of tc_contract_file.contract_view_url
     *
     * @mbggenerated
     */
    public String getContractViewUrl() {
        return contractViewUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.contract_view_url
     *
     * @param contractViewUrl the value for tc_contract_file.contract_view_url
     *
     * @mbggenerated
     */
    public void setContractViewUrl(String contractViewUrl) {
        this.contractViewUrl = contractViewUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.is_deleted
     *
     * @return the value of tc_contract_file.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.is_deleted
     *
     * @param isDeleted the value for tc_contract_file.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.operate_id
     *
     * @return the value of tc_contract_file.operate_id
     *
     * @mbggenerated
     */
    public String getOperateId() {
        return operateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.operate_id
     *
     * @param operateId the value for tc_contract_file.operate_id
     *
     * @mbggenerated
     */
    public void setOperateId(String operateId) {
        this.operateId = operateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.operate_name
     *
     * @return the value of tc_contract_file.operate_name
     *
     * @mbggenerated
     */
    public String getOperateName() {
        return operateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.operate_name
     *
     * @param operateName the value for tc_contract_file.operate_name
     *
     * @mbggenerated
     */
    public void setOperateName(String operateName) {
        this.operateName = operateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.create_date
     *
     * @return the value of tc_contract_file.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.create_date
     *
     * @param createDate the value for tc_contract_file.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_contract_file.update_date
     *
     * @return the value of tc_contract_file.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_contract_file.update_date
     *
     * @param updateDate the value for tc_contract_file.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public String getIsCreatedProject() {
		return isCreatedProject;
	}

	public void setIsCreatedProject(String isCreatedProject) {
		this.isCreatedProject = isCreatedProject;
	}

	public Date getLendBeginTime() {
		return lendBeginTime;
	}
	
	public String getLendBeginTimeStr(){
		try {
			return DateUtil.dateFormat.format(this.lendBeginTime);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return "";
	}
	
	/**
	 * 
	 * <p>三天前</p> 
	 * @return
	 * @author: lxfeng  
	 * @date: Created on 2018-3-16 下午2:32:28
	 */
	public Date getLendBeginTimeThreeDaysAgo(){
		Calendar c = Calendar.getInstance();
		c.setTime(this.lendBeginTime);
		c.add(Calendar.DATE, -3);
		return c.getTime();
	}
	
	/**
	 * 
	 * <p>七天前</p> 
	 * @return
	 * @author: lxfeng  
	 * @date: Created on 2018-3-16 下午2:32:28
	 */
	public Date getLendBeginTimeSevenDaysAgo(){
		Calendar c = Calendar.getInstance();
		c.setTime(this.lendBeginTime);
		c.add(Calendar.DATE, -7);
		return c.getTime();
	}

	public void setLendBeginTime(Date lendBeginTime) {
		this.lendBeginTime = lendBeginTime;
	}

	public double getTotalAmount() {
		return totalAmount;
	}
	
	/**
	 * 月租金
	 * @return
	 */
	public double getOneMonthAmount(){
		return Double.parseDouble(getData("oneMonthAmount").toString());
	}
	
	/**
	 * 
	 * <p>单次借款金额</p> 
	 * @return
	 * @author: lxfeng  
	 * @date: Created on 2018-3-14 上午10:19:54
	 */
	public double getAmount(){
		//单次借款金额=（月租金*放款方式对应的月数*折扣率）/100取整*100
		double mul = MoneyUtil.mul(MoneyUtil.mul(getOneMonthAmount(), lendMonth), getRate());
		return MoneyUtil.mul(MoneyUtil.div(mul, 100d, 0), 100);
	}

	public void setTotalAmount(double totalAmount) {
		this.totalAmount = totalAmount;
	}

	public Integer getLendMonth() {
		return lendMonth;
	}
	
	/**
	 * 
	 * <p>借款天数</p> 
	 * @return
	 * @author: lxfeng  
	 * @date: Created on 2018-3-14 上午10:20:07
	 */
	public Integer getDay(){
		try {
			return this.lendMonth * 30;
		} catch (Exception e) {
			e.printStackTrace();
		}
		return 0;
	}

	public void setLendMonth(Integer lendMonth) {
		this.lendMonth = lendMonth;
	}

	public Integer getLendCount() {
		return lendCount;
	}

	public void setLendCount(Integer lendCount) {
		this.lendCount = lendCount;
	}
	
	/**
	 * 是否有递增 0：无     1：租金递增
	 */
	public Integer getHasIncrease(){
		return Integer.parseInt(this.getData("hasIncrease").toString());
	}
	
	/**
	 * 递增方式 1：一次性递增	2：逐年递增
	 * @return
	 */
	public Integer getIncreaseType(){
		return Integer.parseInt(this.getData("increaseType").toString());
	}
	
	/**
	 * 递增开始年份
	 */
	public Integer getIncreaseYear(){
		return Integer.parseInt(this.getData("increaseYear").toString());
	}
	
	/**
	 * 递增幅度 保留2位小数
	 * @return
	 */
	public double getIncreasePercent(){
		return MoneyUtil.div(Integer.parseInt(this.getData("increasePercent").toString()), 100, 2);
	}
	
	/**
	 * 折扣利率
	 * @return
	 */
	public double getRate(){
		return Double.parseDouble(getData("rate").toString());
	}
	
	/**
	 * 获取当期次的借款金额
	 * @param period 期次
	 * @return
	 */
	public double getSingleMonthAmount(Integer period) throws Exception{
		System.err.println("是否有递增（0=无     1=租金递增）：" + getHasIncrease());
		System.err.println("递增方式（ 1=一次性递增	2=逐年递增）：" + getIncreaseType());
		System.err.println("递增开始年份：" + getIncreaseYear());
		System.err.println("递增幅度：" + getIncreasePercent());
		
		if (this.getHasIncrease() == 0) {//无递增
			return getAmount();
		}else if(this.getHasIncrease() == 1){//有递增
			Integer currentMonth = this.lendMonth * period + 1;		//当前月
			Integer IncrementMonth = (this.getIncreaseYear() - 1) * 12;		//递增开始月份 
			if (this.getIncreaseType() == 1) {//1：一次性递增
				if(currentMonth < IncrementMonth){
					return getAmount();
				}else{
					//单次借款金额=（（1+递增幅度）* 月租金*放款方式对应的月数*折扣率）/100取整*100
					double mul = MoneyUtil.mul(MoneyUtil.mul(MoneyUtil.mul((1 + this.getIncreasePercent()), getOneMonthAmount()), lendMonth), this.getRate());
					return MoneyUtil.mul(MoneyUtil.div(mul, 100d, 0), 100);
				}
			}else if(this.getIncreaseType() == 2){//2：逐年递增
				System.err.print("当前月：" + currentMonth + " 递增开始月：" + IncrementMonth + " 借款金额：");
				if (currentMonth <= IncrementMonth) {
					//单次借款金额=（月租金*放款方式对应的月数*折扣率）/100取整*100
					double amount = getAmount();
					System.err.println(amount);
					return amount;
				}else{
					Integer M = (currentMonth - IncrementMonth) / 12 + 1;
					//单次借款金额=（（1+递增幅度）^M * 月租金*放款方式对应的月数*折扣率）/100取整*100
					double mul = MoneyUtil.mul(MoneyUtil.mul(MoneyUtil.mul(Math.pow((1 + this.getIncreasePercent()),M), getOneMonthAmount()), lendMonth), this.getRate());
					double mul2 = MoneyUtil.mul(MoneyUtil.div(mul, 100d, 0), 100);
					System.err.println(mul2);
					return mul2;
				}
			}
		}
		return 0d;
	}
	
	public String getAddress(){
		return this.getData("address").toString();
	}
	
	public static void main(String[] args) {
		/*Integer a = 8;
		Integer b = 12;
		System.out.println(a/b);*/
		
		System.out.println(1/12);
	}
	

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_contract_file
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ContractFile other = (ContractFile) that;
        return (this.getIdx() == null ? other.getIdx() == null : this.getIdx().equals(other.getIdx()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLandlordId() == null ? other.getLandlordId() == null : this.getLandlordId().equals(other.getLandlordId()))
            && (this.getLandlordName() == null ? other.getLandlordName() == null : this.getLandlordName().equals(other.getLandlordName()))
            && (this.getChannelUserId() == null ? other.getChannelUserId() == null : this.getChannelUserId().equals(other.getChannelUserId()))
            && (this.getContractId() == null ? other.getContractId() == null : this.getContractId().equals(other.getContractId()))
            && (this.getData() == null ? other.getData() == null : this.getData().equals(other.getData()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getShowStatus() == null ? other.getShowStatus() == null : this.getShowStatus().equals(other.getShowStatus()))
            && (this.getContractDownloadUrl() == null ? other.getContractDownloadUrl() == null : this.getContractDownloadUrl().equals(other.getContractDownloadUrl()))
            && (this.getContractViewUrl() == null ? other.getContractViewUrl() == null : this.getContractViewUrl().equals(other.getContractViewUrl()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()))
            && (this.getOperateId() == null ? other.getOperateId() == null : this.getOperateId().equals(other.getOperateId()))
            && (this.getOperateName() == null ? other.getOperateName() == null : this.getOperateName().equals(other.getOperateName()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_contract_file
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdx() == null) ? 0 : getIdx().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLandlordId() == null) ? 0 : getLandlordId().hashCode());
        result = prime * result + ((getLandlordName() == null) ? 0 : getLandlordName().hashCode());
        result = prime * result + ((getChannelUserId() == null) ? 0 : getChannelUserId().hashCode());
        result = prime * result + ((getContractId() == null) ? 0 : getContractId().hashCode());
        result = prime * result + ((getData() == null) ? 0 : getData().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getShowStatus() == null) ? 0 : getShowStatus().hashCode());
        result = prime * result + ((getContractDownloadUrl() == null) ? 0 : getContractDownloadUrl().hashCode());
        result = prime * result + ((getContractViewUrl() == null) ? 0 : getContractViewUrl().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        result = prime * result + ((getOperateId() == null) ? 0 : getOperateId().hashCode());
        result = prime * result + ((getOperateName() == null) ? 0 : getOperateName().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }

    @Override
	public String toString() {
		return "ContractFile [idx=" + idx + ", id=" + id + ", landlordId="
				+ landlordId + ", landlordName=" + landlordName
				+ ", channelUserId=" + channelUserId + ", contractId="
				+ contractId + ", data=" + data + ", status=" + status
				+ ", showStatus=" + showStatus + ", contractDownloadUrl="
				+ contractDownloadUrl + ", contractViewUrl=" + contractViewUrl
				+ ", isDeleted=" + isDeleted + ", operateId=" + operateId
				+ ", operateName=" + operateName + ", createDate=" + createDate
				+ ", updateDate=" + updateDate + ", isCreatedProject="
				+ isCreatedProject + "]";
	}
}