package com.goochou.p2b.model;

import java.util.Date;

public class CustomerList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_list.id
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_list.admin_id
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_list.user_id
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_list.create_time
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    private Date createTime;
    
    private Date updateTime;
    
    private String tag;
    
    private String adminName;
    
    private String mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_list.id
     *
     * @return the value of customer_list.id
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_list.id
     *
     * @param id the value for customer_list.id
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_list.admin_id
     *
     * @return the value of customer_list.admin_id
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_list.admin_id
     *
     * @param adminId the value for customer_list.admin_id
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_list.user_id
     *
     * @return the value of customer_list.user_id
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_list.user_id
     *
     * @param userId the value for customer_list.user_id
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_list.create_time
     *
     * @return the value of customer_list.create_time
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_list.create_time
     *
     * @param createTime the value for customer_list.create_time
     *
     * @mbggenerated Mon Jul 11 13:31:44 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getAdminName() {
		return adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	
    
}