package com.goochou.p2b.model;

import java.util.Date;

public class Icon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column icon.id
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column icon.key
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column icon.title
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column icon.link
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column icon.seq
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column icon.create_time
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column icon.id
     *
     * @return the value of icon.id
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column icon.id
     *
     * @param id the value for icon.id
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column icon.key
     *
     * @return the value of icon.key
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column icon.key
     *
     * @param key the value for icon.key
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column icon.title
     *
     * @return the value of icon.title
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column icon.title
     *
     * @param title the value for icon.title
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column icon.link
     *
     * @return the value of icon.link
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column icon.link
     *
     * @param link the value for icon.link
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column icon.seq
     *
     * @return the value of icon.seq
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column icon.seq
     *
     * @param seq the value for icon.seq
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column icon.create_time
     *
     * @return the value of icon.create_time
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column icon.create_time
     *
     * @param createTime the value for icon.create_time
     *
     * @mbggenerated Mon May 27 10:19:35 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
 // ----
    private String version;
    private String path;
    private String subtitle;
    private String pathGray;

    public String getPathGray() {
        return pathGray;
    }

    public void setPathGray(String pathGray) {
        this.pathGray = pathGray;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getSubtitle() {
        return subtitle;
    }
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }
}