package com.goochou.p2b.model;

import java.io.Serializable;
import java.util.Date;

public class MallActivitySecondKill implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.activity_id
     *
     * @mbg.generated
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.good_id
     *
     * @mbg.generated
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.kill_time
     *
     * @mbg.generated
     */
    private Integer killTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.week_day
     *
     * @mbg.generated
     */
    private Integer weekDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.price
     *
     * @mbg.generated
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.member_price
     *
     * @mbg.generated
     */
    private Long memberPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.stock_count
     *
     * @mbg.generated
     */
    private Integer stockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.saled_count
     *
     * @mbg.generated
     */
    private Integer saledCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.limit_count
     *
     * @mbg.generated
     */
    private Integer limitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.enable
     *
     * @mbg.generated
     */
    private Integer enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_activity_second_kill.is_on_shelves
     *
     * @mbg.generated
     */
    private Integer isOnShelves;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.id
     *
     * @return the value of t_mall_activity_second_kill.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.id
     *
     * @param id the value for t_mall_activity_second_kill.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.activity_id
     *
     * @return the value of t_mall_activity_second_kill.activity_id
     *
     * @mbg.generated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.activity_id
     *
     * @param activityId the value for t_mall_activity_second_kill.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.good_id
     *
     * @return the value of t_mall_activity_second_kill.good_id
     *
     * @mbg.generated
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.good_id
     *
     * @param goodId the value for t_mall_activity_second_kill.good_id
     *
     * @mbg.generated
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.start_time
     *
     * @return the value of t_mall_activity_second_kill.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.start_time
     *
     * @param startTime the value for t_mall_activity_second_kill.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.kill_time
     *
     * @return the value of t_mall_activity_second_kill.kill_time
     *
     * @mbg.generated
     */
    public Integer getKillTime() {
        return killTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.kill_time
     *
     * @param killTime the value for t_mall_activity_second_kill.kill_time
     *
     * @mbg.generated
     */
    public void setKillTime(Integer killTime) {
        this.killTime = killTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.week_day
     *
     * @return the value of t_mall_activity_second_kill.week_day
     *
     * @mbg.generated
     */
    public Integer getWeekDay() {
        return weekDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.week_day
     *
     * @param weekDay the value for t_mall_activity_second_kill.week_day
     *
     * @mbg.generated
     */
    public void setWeekDay(Integer weekDay) {
        this.weekDay = weekDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.price
     *
     * @return the value of t_mall_activity_second_kill.price
     *
     * @mbg.generated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.price
     *
     * @param price the value for t_mall_activity_second_kill.price
     *
     * @mbg.generated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.member_price
     *
     * @return the value of t_mall_activity_second_kill.member_price
     *
     * @mbg.generated
     */
    public Long getMemberPrice() {
        return memberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.member_price
     *
     * @param memberPrice the value for t_mall_activity_second_kill.member_price
     *
     * @mbg.generated
     */
    public void setMemberPrice(Long memberPrice) {
        this.memberPrice = memberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.stock_count
     *
     * @return the value of t_mall_activity_second_kill.stock_count
     *
     * @mbg.generated
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.stock_count
     *
     * @param stockCount the value for t_mall_activity_second_kill.stock_count
     *
     * @mbg.generated
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.saled_count
     *
     * @return the value of t_mall_activity_second_kill.saled_count
     *
     * @mbg.generated
     */
    public Integer getSaledCount() {
        return saledCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.saled_count
     *
     * @param saledCount the value for t_mall_activity_second_kill.saled_count
     *
     * @mbg.generated
     */
    public void setSaledCount(Integer saledCount) {
        this.saledCount = saledCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.limit_count
     *
     * @return the value of t_mall_activity_second_kill.limit_count
     *
     * @mbg.generated
     */
    public Integer getLimitCount() {
        return limitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.limit_count
     *
     * @param limitCount the value for t_mall_activity_second_kill.limit_count
     *
     * @mbg.generated
     */
    public void setLimitCount(Integer limitCount) {
        this.limitCount = limitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.title
     *
     * @return the value of t_mall_activity_second_kill.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.title
     *
     * @param title the value for t_mall_activity_second_kill.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.create_time
     *
     * @return the value of t_mall_activity_second_kill.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.create_time
     *
     * @param createTime the value for t_mall_activity_second_kill.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.enable
     *
     * @return the value of t_mall_activity_second_kill.enable
     *
     * @mbg.generated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.enable
     *
     * @param enable the value for t_mall_activity_second_kill.enable
     *
     * @mbg.generated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_activity_second_kill.is_on_shelves
     *
     * @return the value of t_mall_activity_second_kill.is_on_shelves
     *
     * @mbg.generated
     */
    public Integer getIsOnShelves() {
        return isOnShelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_activity_second_kill.is_on_shelves
     *
     * @param isOnShelves the value for t_mall_activity_second_kill.is_on_shelves
     *
     * @mbg.generated
     */
    public void setIsOnShelves(Integer isOnShelves) {
        this.isOnShelves = isOnShelves;
    }
}