package com.goochou.p2b.model;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;
import com.goochou.p2b.constant.client.ClientConstants;
import com.goochou.p2b.utils.FormatUtil;
import com.goochou.p2b.utils.StringUtils;

public class TrackDeviceView implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.updated_at
	 * @mbg.generated
	 */
	private String updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.uuid
	 * @mbg.generated
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.device_type
	 * @mbg.generated
	 */
	private String deviceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.hardware_version
	 * @mbg.generated
	 */
	private String hardwareVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.firmware_version
	 * @mbg.generated
	 */
	private String firmwareVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.company_id
	 * @mbg.generated
	 */
	private String companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.company_name
	 * @mbg.generated
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.imsi
	 * @mbg.generated
	 */
	private String imsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.iccid
	 * @mbg.generated
	 */
	private String iccid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.sim_number
	 * @mbg.generated
	 */
	private String simNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.mac
	 * @mbg.generated
	 */
	private String mac;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.mark
	 * @mbg.generated
	 */
	private String mark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.battery_voltage
	 * @mbg.generated
	 */
	private String batteryVoltage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.temperature
	 * @mbg.generated
	 */
	private String temperature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.survive
	 * @mbg.generated
	 */
	private String survive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.stock_time
	 * @mbg.generated
	 */
	private String stockTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.status
	 * @mbg.generated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.signal_strength
	 * @mbg.generated
	 */
	private String signalStrength;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.bit_error_rate
	 * @mbg.generated
	 */
	private String bitErrorRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.radio_access_technology
	 * @mbg.generated
	 */
	private String radioAccessTechnology;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.network_operator
	 * @mbg.generated
	 */
	private String networkOperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.gps_signal_strength
	 * @mbg.generated
	 */
	private String gpsSignalStrength;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.battery_power
	 * @mbg.generated
	 */
	private String batteryPower;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.longitude
	 * @mbg.generated
	 */
	private String longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.latitude
	 * @mbg.generated
	 */
	private String latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.point_location
	 * @mbg.generated
	 */
	private String pointLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.location_timestamp
	 * @mbg.generated
	 */
	private String locationTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.beh_timestamp
	 * @mbg.generated
	 */
	private String behTimestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.sync_at
	 * @mbg.generated
	 */
	private Date syncAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.sn
	 * @mbg.generated
	 */
	private String sn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.nickname
	 * @mbg.generated
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.project_id
	 * @mbg.generated
	 */
	private Integer projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.ear_number
	 * @mbg.generated
	 */
	private String earNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.real_ear_number
	 * @mbg.generated
	 */
	private String realEarNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.prairie_value
	 * @mbg.generated
	 */
	private String prairieValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.sex
	 * @mbg.generated
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.weight
	 * @mbg.generated
	 */
	private Double weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.prairie_name
	 * @mbg.generated
	 */
	private String prairieName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.path
	 * @mbg.generated
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.pin_zhong
	 * @mbg.generated
	 */
	private String pinZhong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.chan_di_lai_yuan
	 * @mbg.generated
	 */
	private String chanDiLaiYuan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.yue_ling
	 * @mbg.generated
	 */
	private String yueLing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column track_device_view.jian_kang_zhuang_kuang
	 * @mbg.generated
	 */
	private String jianKangZhuangKuang;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table track_device_view
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.id
	 * @return  the value of track_device_view.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.id
	 * @param id  the value for track_device_view.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.updated_at
	 * @return  the value of track_device_view.updated_at
	 * @mbg.generated
	 */
	public String getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.updated_at
	 * @param updatedAt  the value for track_device_view.updated_at
	 * @mbg.generated
	 */
	public void setUpdatedAt(String updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.uuid
	 * @return  the value of track_device_view.uuid
	 * @mbg.generated
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.uuid
	 * @param uuid  the value for track_device_view.uuid
	 * @mbg.generated
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.device_type
	 * @return  the value of track_device_view.device_type
	 * @mbg.generated
	 */
	public String getDeviceType() {
		return deviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.device_type
	 * @param deviceType  the value for track_device_view.device_type
	 * @mbg.generated
	 */
	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.hardware_version
	 * @return  the value of track_device_view.hardware_version
	 * @mbg.generated
	 */
	public String getHardwareVersion() {
		return hardwareVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.hardware_version
	 * @param hardwareVersion  the value for track_device_view.hardware_version
	 * @mbg.generated
	 */
	public void setHardwareVersion(String hardwareVersion) {
		this.hardwareVersion = hardwareVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.firmware_version
	 * @return  the value of track_device_view.firmware_version
	 * @mbg.generated
	 */
	public String getFirmwareVersion() {
		return firmwareVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.firmware_version
	 * @param firmwareVersion  the value for track_device_view.firmware_version
	 * @mbg.generated
	 */
	public void setFirmwareVersion(String firmwareVersion) {
		this.firmwareVersion = firmwareVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.company_id
	 * @return  the value of track_device_view.company_id
	 * @mbg.generated
	 */
	public String getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.company_id
	 * @param companyId  the value for track_device_view.company_id
	 * @mbg.generated
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.company_name
	 * @return  the value of track_device_view.company_name
	 * @mbg.generated
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.company_name
	 * @param companyName  the value for track_device_view.company_name
	 * @mbg.generated
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.imsi
	 * @return  the value of track_device_view.imsi
	 * @mbg.generated
	 */
	public String getImsi() {
		return imsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.imsi
	 * @param imsi  the value for track_device_view.imsi
	 * @mbg.generated
	 */
	public void setImsi(String imsi) {
		this.imsi = imsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.iccid
	 * @return  the value of track_device_view.iccid
	 * @mbg.generated
	 */
	public String getIccid() {
		return iccid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.iccid
	 * @param iccid  the value for track_device_view.iccid
	 * @mbg.generated
	 */
	public void setIccid(String iccid) {
		this.iccid = iccid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.sim_number
	 * @return  the value of track_device_view.sim_number
	 * @mbg.generated
	 */
	public String getSimNumber() {
		return simNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.sim_number
	 * @param simNumber  the value for track_device_view.sim_number
	 * @mbg.generated
	 */
	public void setSimNumber(String simNumber) {
		this.simNumber = simNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.mac
	 * @return  the value of track_device_view.mac
	 * @mbg.generated
	 */
	public String getMac() {
		return mac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.mac
	 * @param mac  the value for track_device_view.mac
	 * @mbg.generated
	 */
	public void setMac(String mac) {
		this.mac = mac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.mark
	 * @return  the value of track_device_view.mark
	 * @mbg.generated
	 */
	public String getMark() {
		return mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.mark
	 * @param mark  the value for track_device_view.mark
	 * @mbg.generated
	 */
	public void setMark(String mark) {
		this.mark = mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.battery_voltage
	 * @return  the value of track_device_view.battery_voltage
	 * @mbg.generated
	 */
	public String getBatteryVoltage() {
		return batteryVoltage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.battery_voltage
	 * @param batteryVoltage  the value for track_device_view.battery_voltage
	 * @mbg.generated
	 */
	public void setBatteryVoltage(String batteryVoltage) {
		this.batteryVoltage = batteryVoltage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.temperature
	 * @return  the value of track_device_view.temperature
	 * @mbg.generated
	 */
	public String getTemperature() {
		return temperature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.temperature
	 * @param temperature  the value for track_device_view.temperature
	 * @mbg.generated
	 */
	public void setTemperature(String temperature) {
		this.temperature = temperature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.survive
	 * @return  the value of track_device_view.survive
	 * @mbg.generated
	 */
	public String getSurvive() {
		return survive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.survive
	 * @param survive  the value for track_device_view.survive
	 * @mbg.generated
	 */
	public void setSurvive(String survive) {
		this.survive = survive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.stock_time
	 * @return  the value of track_device_view.stock_time
	 * @mbg.generated
	 */
	public String getStockTime() {
		return stockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.stock_time
	 * @param stockTime  the value for track_device_view.stock_time
	 * @mbg.generated
	 */
	public void setStockTime(String stockTime) {
		this.stockTime = stockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.status
	 * @return  the value of track_device_view.status
	 * @mbg.generated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.status
	 * @param status  the value for track_device_view.status
	 * @mbg.generated
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.signal_strength
	 * @return  the value of track_device_view.signal_strength
	 * @mbg.generated
	 */
	public String getSignalStrength() {
		return signalStrength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.signal_strength
	 * @param signalStrength  the value for track_device_view.signal_strength
	 * @mbg.generated
	 */
	public void setSignalStrength(String signalStrength) {
		this.signalStrength = signalStrength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.bit_error_rate
	 * @return  the value of track_device_view.bit_error_rate
	 * @mbg.generated
	 */
	public String getBitErrorRate() {
		return bitErrorRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.bit_error_rate
	 * @param bitErrorRate  the value for track_device_view.bit_error_rate
	 * @mbg.generated
	 */
	public void setBitErrorRate(String bitErrorRate) {
		this.bitErrorRate = bitErrorRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.radio_access_technology
	 * @return  the value of track_device_view.radio_access_technology
	 * @mbg.generated
	 */
	public String getRadioAccessTechnology() {
		return radioAccessTechnology;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.radio_access_technology
	 * @param radioAccessTechnology  the value for track_device_view.radio_access_technology
	 * @mbg.generated
	 */
	public void setRadioAccessTechnology(String radioAccessTechnology) {
		this.radioAccessTechnology = radioAccessTechnology;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.network_operator
	 * @return  the value of track_device_view.network_operator
	 * @mbg.generated
	 */
	public String getNetworkOperator() {
		return networkOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.network_operator
	 * @param networkOperator  the value for track_device_view.network_operator
	 * @mbg.generated
	 */
	public void setNetworkOperator(String networkOperator) {
		this.networkOperator = networkOperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.gps_signal_strength
	 * @return  the value of track_device_view.gps_signal_strength
	 * @mbg.generated
	 */
	public String getGpsSignalStrength() {
		return gpsSignalStrength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.gps_signal_strength
	 * @param gpsSignalStrength  the value for track_device_view.gps_signal_strength
	 * @mbg.generated
	 */
	public void setGpsSignalStrength(String gpsSignalStrength) {
		this.gpsSignalStrength = gpsSignalStrength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.battery_power
	 * @return  the value of track_device_view.battery_power
	 * @mbg.generated
	 */
	public String getBatteryPower() {
		return batteryPower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.battery_power
	 * @param batteryPower  the value for track_device_view.battery_power
	 * @mbg.generated
	 */
	public void setBatteryPower(String batteryPower) {
		this.batteryPower = batteryPower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.longitude
	 * @return  the value of track_device_view.longitude
	 * @mbg.generated
	 */
	public String getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.longitude
	 * @param longitude  the value for track_device_view.longitude
	 * @mbg.generated
	 */
	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.latitude
	 * @return  the value of track_device_view.latitude
	 * @mbg.generated
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.latitude
	 * @param latitude  the value for track_device_view.latitude
	 * @mbg.generated
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.point_location
	 * @return  the value of track_device_view.point_location
	 * @mbg.generated
	 */
	public String getPointLocation() {
		return pointLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.point_location
	 * @param pointLocation  the value for track_device_view.point_location
	 * @mbg.generated
	 */
	public void setPointLocation(String pointLocation) {
		this.pointLocation = pointLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.location_timestamp
	 * @return  the value of track_device_view.location_timestamp
	 * @mbg.generated
	 */
	public String getLocationTimestamp() {
		return locationTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.location_timestamp
	 * @param locationTimestamp  the value for track_device_view.location_timestamp
	 * @mbg.generated
	 */
	public void setLocationTimestamp(String locationTimestamp) {
		this.locationTimestamp = locationTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.beh_timestamp
	 * @return  the value of track_device_view.beh_timestamp
	 * @mbg.generated
	 */
	public String getBehTimestamp() {
		return behTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.beh_timestamp
	 * @param behTimestamp  the value for track_device_view.beh_timestamp
	 * @mbg.generated
	 */
	public void setBehTimestamp(String behTimestamp) {
		this.behTimestamp = behTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.sync_at
	 * @return  the value of track_device_view.sync_at
	 * @mbg.generated
	 */
	public Date getSyncAt() {
		return syncAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.sync_at
	 * @param syncAt  the value for track_device_view.sync_at
	 * @mbg.generated
	 */
	public void setSyncAt(Date syncAt) {
		this.syncAt = syncAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.sn
	 * @return  the value of track_device_view.sn
	 * @mbg.generated
	 */
	public String getSn() {
		return sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.sn
	 * @param sn  the value for track_device_view.sn
	 * @mbg.generated
	 */
	public void setSn(String sn) {
		this.sn = sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.nickname
	 * @return  the value of track_device_view.nickname
	 * @mbg.generated
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.nickname
	 * @param nickname  the value for track_device_view.nickname
	 * @mbg.generated
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.is_virtual
	 * @return  the value of track_device_view.is_virtual
	 * @mbg.generated
	 */
	public Boolean getIsVirtual() {
		return isVirtual;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.is_virtual
	 * @param isVirtual  the value for track_device_view.is_virtual
	 * @mbg.generated
	 */
	public void setIsVirtual(Boolean isVirtual) {
		this.isVirtual = isVirtual;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.project_id
	 * @return  the value of track_device_view.project_id
	 * @mbg.generated
	 */
	public Integer getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.project_id
	 * @param projectId  the value for track_device_view.project_id
	 * @mbg.generated
	 */
	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.title
	 * @return  the value of track_device_view.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.title
	 * @param title  the value for track_device_view.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.ear_number
	 * @return  the value of track_device_view.ear_number
	 * @mbg.generated
	 */
	public String getEarNumber() {
		return earNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.ear_number
	 * @param earNumber  the value for track_device_view.ear_number
	 * @mbg.generated
	 */
	public void setEarNumber(String earNumber) {
		this.earNumber = earNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.real_ear_number
	 * @return  the value of track_device_view.real_ear_number
	 * @mbg.generated
	 */
	public String getRealEarNumber() {
		return realEarNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.real_ear_number
	 * @param realEarNumber  the value for track_device_view.real_ear_number
	 * @mbg.generated
	 */
	public void setRealEarNumber(String realEarNumber) {
		this.realEarNumber = realEarNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.prairie_value
	 * @return  the value of track_device_view.prairie_value
	 * @mbg.generated
	 */
	public String getPrairieValue() {
		return prairieValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.prairie_value
	 * @param prairieValue  the value for track_device_view.prairie_value
	 * @mbg.generated
	 */
	public void setPrairieValue(String prairieValue) {
		this.prairieValue = prairieValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.sex
	 * @return  the value of track_device_view.sex
	 * @mbg.generated
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.sex
	 * @param sex  the value for track_device_view.sex
	 * @mbg.generated
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.weight
	 * @return  the value of track_device_view.weight
	 * @mbg.generated
	 */
	public Double getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.weight
	 * @param weight  the value for track_device_view.weight
	 * @mbg.generated
	 */
	public void setWeight(Double weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.prairie_name
	 * @return  the value of track_device_view.prairie_name
	 * @mbg.generated
	 */
	public String getPrairieName() {
		return prairieName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.prairie_name
	 * @param prairieName  the value for track_device_view.prairie_name
	 * @mbg.generated
	 */
	public void setPrairieName(String prairieName) {
		this.prairieName = prairieName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.path
	 * @return  the value of track_device_view.path
	 * @mbg.generated
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.path
	 * @param path  the value for track_device_view.path
	 * @mbg.generated
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.pin_zhong
	 * @return  the value of track_device_view.pin_zhong
	 * @mbg.generated
	 */
	public String getPinZhong() {
		return pinZhong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.pin_zhong
	 * @param pinZhong  the value for track_device_view.pin_zhong
	 * @mbg.generated
	 */
	public void setPinZhong(String pinZhong) {
		this.pinZhong = pinZhong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.chan_di_lai_yuan
	 * @return  the value of track_device_view.chan_di_lai_yuan
	 * @mbg.generated
	 */
	public String getChanDiLaiYuan() {
		return chanDiLaiYuan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.chan_di_lai_yuan
	 * @param chanDiLaiYuan  the value for track_device_view.chan_di_lai_yuan
	 * @mbg.generated
	 */
	public void setChanDiLaiYuan(String chanDiLaiYuan) {
		this.chanDiLaiYuan = chanDiLaiYuan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.yue_ling
	 * @return  the value of track_device_view.yue_ling
	 * @mbg.generated
	 */
	public String getYueLing() {
		return yueLing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.yue_ling
	 * @param yueLing  the value for track_device_view.yue_ling
	 * @mbg.generated
	 */
	public void setYueLing(String yueLing) {
		this.yueLing = yueLing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column track_device_view.jian_kang_zhuang_kuang
	 * @return  the value of track_device_view.jian_kang_zhuang_kuang
	 * @mbg.generated
	 */
	public String getJianKangZhuangKuang() {
		return jianKangZhuangKuang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column track_device_view.jian_kang_zhuang_kuang
	 * @param jianKangZhuangKuang  the value for track_device_view.jian_kang_zhuang_kuang
	 * @mbg.generated
	 */
	public void setJianKangZhuangKuang(String jianKangZhuangKuang) {
		this.jianKangZhuangKuang = jianKangZhuangKuang;
	}

	//--------------------------------------------------------------------
	/**
	 * track_device_view.is_virtual,重新生成后删除生成的属性
	 */
	@JSONField(serialize=false)
	private Boolean isVirtual;
	
  	public String getCdnPath() {
  		if (path != null ) {
  			return ClientConstants.ALIBABA_PATH + "upload/" + path;
  		} else {
  			return null;
  		}
  	}
  	
  	public double[] getLongiLatiArray() {
  		
  		if(FormatUtil.isDecimal(this.longitude) && FormatUtil.isDecimal(this.latitude) ) {
  			return new double[]{Double.valueOf(this.longitude),Double.valueOf(this.latitude)};
  		}else {
  			return null;
  		}
  	}
  	
  	public final static SimpleDateFormat DATE_PARSE=new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
  	public final static SimpleDateFormat DATE_PARSE_MILLISECOND=new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
	private final static SimpleDateFormat DATE_FORMAT=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	
	static private String parseTZDateStr(String sourceDateStr) {
		if(!StringUtils.isBlank(sourceDateStr)) {
			try {
				Date resultDate=DATE_PARSE.parse(sourceDateStr);
				return DATE_FORMAT.format(resultDate);
			} catch (Exception e) {
				return sourceDateStr;
			}
		}else {
			return "";
		}
	}
	static private String parseTZMillisecondDateStr(String sourceDateStr) {
		if(!StringUtils.isBlank(sourceDateStr)) {
			try {
				Date resultDate=DATE_PARSE_MILLISECOND.parse(sourceDateStr);
				return DATE_FORMAT.format(resultDate);
			} catch (Exception e) {
				return sourceDateStr;
			}
		}else {
			return "";
		}
	}
	//定位时间
	public String getLocationTimestampStr() {
		return TrackDeviceView.parseTZDateStr(this.locationTimestamp);
	}
	//出厂时间
	public String getStockTimeStr() {
		return TrackDeviceView.parseTZDateStr(this.stockTime);
	}
	//最后通信时间
	public String getUpdatedAtStr() {
		return TrackDeviceView.parseTZMillisecondDateStr(this.updatedAt);
	}
	//最后拉取时间
	public String getSyncAtStr() {
		if(this.syncAt!=null) {
			return DATE_FORMAT.format(this.syncAt);
		}else {
			return "";
		}
	}
	
	public String getSexStr() {
		//家畜性别   0  公  1  母
		if(StringUtils.isBlank(this.sex)) {
			return "未知";
		}else if("0".equals(this.sex)){
			return "公";
		}else if("1".equals(this.sex)){
			return "母";
		}else{
			return "未知";
		}
	}
	
	public String getWeightStr() {
		if(this.weight==null) {
			return "未知";
		}else{
			return weight+"KG";
		}
	}
}