package com.goochou.p2b.model;

import java.util.ArrayList;
import java.util.List;

public class TunnelHeshiOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public TunnelHeshiOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHlidIsNull() {
            addCriterion("hlid is null");
            return (Criteria) this;
        }

        public Criteria andHlidIsNotNull() {
            addCriterion("hlid is not null");
            return (Criteria) this;
        }

        public Criteria andHlidEqualTo(String value) {
            addCriterion("hlid =", value, "hlid");
            return (Criteria) this;
        }

        public Criteria andHlidNotEqualTo(String value) {
            addCriterion("hlid <>", value, "hlid");
            return (Criteria) this;
        }

        public Criteria andHlidGreaterThan(String value) {
            addCriterion("hlid >", value, "hlid");
            return (Criteria) this;
        }

        public Criteria andHlidGreaterThanOrEqualTo(String value) {
            addCriterion("hlid >=", value, "hlid");
            return (Criteria) this;
        }

        public Criteria andHlidLessThan(String value) {
            addCriterion("hlid <", value, "hlid");
            return (Criteria) this;
        }

        public Criteria andHlidLessThanOrEqualTo(String value) {
            addCriterion("hlid <=", value, "hlid");
            return (Criteria) this;
        }

        public Criteria andHlidLike(String value) {
            addCriterion("hlid like", value, "hlid");
            return (Criteria) this;
        }

        public Criteria andHlidNotLike(String value) {
            addCriterion("hlid not like", value, "hlid");
            return (Criteria) this;
        }

        public Criteria andHlidIn(List<String> values) {
            addCriterion("hlid in", values, "hlid");
            return (Criteria) this;
        }

        public Criteria andHlidNotIn(List<String> values) {
            addCriterion("hlid not in", values, "hlid");
            return (Criteria) this;
        }

        public Criteria andHlidBetween(String value1, String value2) {
            addCriterion("hlid between", value1, value2, "hlid");
            return (Criteria) this;
        }

        public Criteria andHlidNotBetween(String value1, String value2) {
            addCriterion("hlid not between", value1, value2, "hlid");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPayCdIsNull() {
            addCriterion("pay_cd is null");
            return (Criteria) this;
        }

        public Criteria andPayCdIsNotNull() {
            addCriterion("pay_cd is not null");
            return (Criteria) this;
        }

        public Criteria andPayCdEqualTo(String value) {
            addCriterion("pay_cd =", value, "payCd");
            return (Criteria) this;
        }

        public Criteria andPayCdNotEqualTo(String value) {
            addCriterion("pay_cd <>", value, "payCd");
            return (Criteria) this;
        }

        public Criteria andPayCdGreaterThan(String value) {
            addCriterion("pay_cd >", value, "payCd");
            return (Criteria) this;
        }

        public Criteria andPayCdGreaterThanOrEqualTo(String value) {
            addCriterion("pay_cd >=", value, "payCd");
            return (Criteria) this;
        }

        public Criteria andPayCdLessThan(String value) {
            addCriterion("pay_cd <", value, "payCd");
            return (Criteria) this;
        }

        public Criteria andPayCdLessThanOrEqualTo(String value) {
            addCriterion("pay_cd <=", value, "payCd");
            return (Criteria) this;
        }

        public Criteria andPayCdLike(String value) {
            addCriterion("pay_cd like", value, "payCd");
            return (Criteria) this;
        }

        public Criteria andPayCdNotLike(String value) {
            addCriterion("pay_cd not like", value, "payCd");
            return (Criteria) this;
        }

        public Criteria andPayCdIn(List<String> values) {
            addCriterion("pay_cd in", values, "payCd");
            return (Criteria) this;
        }

        public Criteria andPayCdNotIn(List<String> values) {
            addCriterion("pay_cd not in", values, "payCd");
            return (Criteria) this;
        }

        public Criteria andPayCdBetween(String value1, String value2) {
            addCriterion("pay_cd between", value1, value2, "payCd");
            return (Criteria) this;
        }

        public Criteria andPayCdNotBetween(String value1, String value2) {
            addCriterion("pay_cd not between", value1, value2, "payCd");
            return (Criteria) this;
        }

        public Criteria andMbrIdIsNull() {
            addCriterion("mbr_id is null");
            return (Criteria) this;
        }

        public Criteria andMbrIdIsNotNull() {
            addCriterion("mbr_id is not null");
            return (Criteria) this;
        }

        public Criteria andMbrIdEqualTo(String value) {
            addCriterion("mbr_id =", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotEqualTo(String value) {
            addCriterion("mbr_id <>", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdGreaterThan(String value) {
            addCriterion("mbr_id >", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdGreaterThanOrEqualTo(String value) {
            addCriterion("mbr_id >=", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLessThan(String value) {
            addCriterion("mbr_id <", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLessThanOrEqualTo(String value) {
            addCriterion("mbr_id <=", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdLike(String value) {
            addCriterion("mbr_id like", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotLike(String value) {
            addCriterion("mbr_id not like", value, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdIn(List<String> values) {
            addCriterion("mbr_id in", values, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotIn(List<String> values) {
            addCriterion("mbr_id not in", values, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdBetween(String value1, String value2) {
            addCriterion("mbr_id between", value1, value2, "mbrId");
            return (Criteria) this;
        }

        public Criteria andMbrIdNotBetween(String value1, String value2) {
            addCriterion("mbr_id not between", value1, value2, "mbrId");
            return (Criteria) this;
        }

        public Criteria andOCdIsNull() {
            addCriterion("o_cd is null");
            return (Criteria) this;
        }

        public Criteria andOCdIsNotNull() {
            addCriterion("o_cd is not null");
            return (Criteria) this;
        }

        public Criteria andOCdEqualTo(Integer value) {
            addCriterion("o_cd =", value, "oCd");
            return (Criteria) this;
        }

        public Criteria andOCdNotEqualTo(Integer value) {
            addCriterion("o_cd <>", value, "oCd");
            return (Criteria) this;
        }

        public Criteria andOCdGreaterThan(Integer value) {
            addCriterion("o_cd >", value, "oCd");
            return (Criteria) this;
        }

        public Criteria andOCdGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_cd >=", value, "oCd");
            return (Criteria) this;
        }

        public Criteria andOCdLessThan(Integer value) {
            addCriterion("o_cd <", value, "oCd");
            return (Criteria) this;
        }

        public Criteria andOCdLessThanOrEqualTo(Integer value) {
            addCriterion("o_cd <=", value, "oCd");
            return (Criteria) this;
        }

        public Criteria andOCdIn(List<Integer> values) {
            addCriterion("o_cd in", values, "oCd");
            return (Criteria) this;
        }

        public Criteria andOCdNotIn(List<Integer> values) {
            addCriterion("o_cd not in", values, "oCd");
            return (Criteria) this;
        }

        public Criteria andOCdBetween(Integer value1, Integer value2) {
            addCriterion("o_cd between", value1, value2, "oCd");
            return (Criteria) this;
        }

        public Criteria andOCdNotBetween(Integer value1, Integer value2) {
            addCriterion("o_cd not between", value1, value2, "oCd");
            return (Criteria) this;
        }

        public Criteria andPCdIsNull() {
            addCriterion("p_cd is null");
            return (Criteria) this;
        }

        public Criteria andPCdIsNotNull() {
            addCriterion("p_cd is not null");
            return (Criteria) this;
        }

        public Criteria andPCdEqualTo(Integer value) {
            addCriterion("p_cd =", value, "pCd");
            return (Criteria) this;
        }

        public Criteria andPCdNotEqualTo(Integer value) {
            addCriterion("p_cd <>", value, "pCd");
            return (Criteria) this;
        }

        public Criteria andPCdGreaterThan(Integer value) {
            addCriterion("p_cd >", value, "pCd");
            return (Criteria) this;
        }

        public Criteria andPCdGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_cd >=", value, "pCd");
            return (Criteria) this;
        }

        public Criteria andPCdLessThan(Integer value) {
            addCriterion("p_cd <", value, "pCd");
            return (Criteria) this;
        }

        public Criteria andPCdLessThanOrEqualTo(Integer value) {
            addCriterion("p_cd <=", value, "pCd");
            return (Criteria) this;
        }

        public Criteria andPCdIn(List<Integer> values) {
            addCriterion("p_cd in", values, "pCd");
            return (Criteria) this;
        }

        public Criteria andPCdNotIn(List<Integer> values) {
            addCriterion("p_cd not in", values, "pCd");
            return (Criteria) this;
        }

        public Criteria andPCdBetween(Integer value1, Integer value2) {
            addCriterion("p_cd between", value1, value2, "pCd");
            return (Criteria) this;
        }

        public Criteria andPCdNotBetween(Integer value1, Integer value2) {
            addCriterion("p_cd not between", value1, value2, "pCd");
            return (Criteria) this;
        }

        public Criteria andItCntIsNull() {
            addCriterion("it_cnt is null");
            return (Criteria) this;
        }

        public Criteria andItCntIsNotNull() {
            addCriterion("it_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andItCntEqualTo(Integer value) {
            addCriterion("it_cnt =", value, "itCnt");
            return (Criteria) this;
        }

        public Criteria andItCntNotEqualTo(Integer value) {
            addCriterion("it_cnt <>", value, "itCnt");
            return (Criteria) this;
        }

        public Criteria andItCntGreaterThan(Integer value) {
            addCriterion("it_cnt >", value, "itCnt");
            return (Criteria) this;
        }

        public Criteria andItCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("it_cnt >=", value, "itCnt");
            return (Criteria) this;
        }

        public Criteria andItCntLessThan(Integer value) {
            addCriterion("it_cnt <", value, "itCnt");
            return (Criteria) this;
        }

        public Criteria andItCntLessThanOrEqualTo(Integer value) {
            addCriterion("it_cnt <=", value, "itCnt");
            return (Criteria) this;
        }

        public Criteria andItCntIn(List<Integer> values) {
            addCriterion("it_cnt in", values, "itCnt");
            return (Criteria) this;
        }

        public Criteria andItCntNotIn(List<Integer> values) {
            addCriterion("it_cnt not in", values, "itCnt");
            return (Criteria) this;
        }

        public Criteria andItCntBetween(Integer value1, Integer value2) {
            addCriterion("it_cnt between", value1, value2, "itCnt");
            return (Criteria) this;
        }

        public Criteria andItCntNotBetween(Integer value1, Integer value2) {
            addCriterion("it_cnt not between", value1, value2, "itCnt");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Double value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Double value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Double value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Double value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Double value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Double> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Double> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Double value1, Double value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Double value1, Double value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andCCdIsNull() {
            addCriterion("c_cd is null");
            return (Criteria) this;
        }

        public Criteria andCCdIsNotNull() {
            addCriterion("c_cd is not null");
            return (Criteria) this;
        }

        public Criteria andCCdEqualTo(String value) {
            addCriterion("c_cd =", value, "cCd");
            return (Criteria) this;
        }

        public Criteria andCCdNotEqualTo(String value) {
            addCriterion("c_cd <>", value, "cCd");
            return (Criteria) this;
        }

        public Criteria andCCdGreaterThan(String value) {
            addCriterion("c_cd >", value, "cCd");
            return (Criteria) this;
        }

        public Criteria andCCdGreaterThanOrEqualTo(String value) {
            addCriterion("c_cd >=", value, "cCd");
            return (Criteria) this;
        }

        public Criteria andCCdLessThan(String value) {
            addCriterion("c_cd <", value, "cCd");
            return (Criteria) this;
        }

        public Criteria andCCdLessThanOrEqualTo(String value) {
            addCriterion("c_cd <=", value, "cCd");
            return (Criteria) this;
        }

        public Criteria andCCdLike(String value) {
            addCriterion("c_cd like", value, "cCd");
            return (Criteria) this;
        }

        public Criteria andCCdNotLike(String value) {
            addCriterion("c_cd not like", value, "cCd");
            return (Criteria) this;
        }

        public Criteria andCCdIn(List<String> values) {
            addCriterion("c_cd in", values, "cCd");
            return (Criteria) this;
        }

        public Criteria andCCdNotIn(List<String> values) {
            addCriterion("c_cd not in", values, "cCd");
            return (Criteria) this;
        }

        public Criteria andCCdBetween(String value1, String value2) {
            addCriterion("c_cd between", value1, value2, "cCd");
            return (Criteria) this;
        }

        public Criteria andCCdNotBetween(String value1, String value2) {
            addCriterion("c_cd not between", value1, value2, "cCd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 09 13:42:58 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}