package com.goochou.p2b.model;

import java.io.Serializable;
import java.util.Date;

public class UserSignAward implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign_award.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign_award.is_invested
     *
     * @mbggenerated
     */
    private Integer isInvested;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign_award.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign_award.prize_type
     *
     * @mbggenerated
     */
    private String prizeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign_award.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign_award.amount
     *
     * @mbggenerated
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign_award.rule
     *
     * @mbggenerated
     */
    private String rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign_award.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign_award.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sign_award.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_sign_award
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign_award.id
     *
     * @return the value of user_sign_award.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign_award.id
     *
     * @param id the value for user_sign_award.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign_award.is_invested
     *
     * @return the value of user_sign_award.is_invested
     *
     * @mbggenerated
     */
    public Integer getIsInvested() {
        return isInvested;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign_award.is_invested
     *
     * @param isInvested the value for user_sign_award.is_invested
     *
     * @mbggenerated
     */
    public void setIsInvested(Integer isInvested) {
        this.isInvested = isInvested;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign_award.user_id
     *
     * @return the value of user_sign_award.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign_award.user_id
     *
     * @param userId the value for user_sign_award.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign_award.prize_type
     *
     * @return the value of user_sign_award.prize_type
     *
     * @mbggenerated
     */
    public String getPrizeType() {
        return prizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign_award.prize_type
     *
     * @param prizeType the value for user_sign_award.prize_type
     *
     * @mbggenerated
     */
    public void setPrizeType(String prizeType) {
        this.prizeType = prizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign_award.count
     *
     * @return the value of user_sign_award.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign_award.count
     *
     * @param count the value for user_sign_award.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign_award.amount
     *
     * @return the value of user_sign_award.amount
     *
     * @mbggenerated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign_award.amount
     *
     * @param amount the value for user_sign_award.amount
     *
     * @mbggenerated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign_award.rule
     *
     * @return the value of user_sign_award.rule
     *
     * @mbggenerated
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign_award.rule
     *
     * @param rule the value for user_sign_award.rule
     *
     * @mbggenerated
     */
    public void setRule(String rule) {
        this.rule = rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign_award.is_deleted
     *
     * @return the value of user_sign_award.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign_award.is_deleted
     *
     * @param isDeleted the value for user_sign_award.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign_award.create_date
     *
     * @return the value of user_sign_award.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign_award.create_date
     *
     * @param createDate the value for user_sign_award.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sign_award.update_date
     *
     * @return the value of user_sign_award.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sign_award.update_date
     *
     * @param updateDate the value for user_sign_award.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign_award
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserSignAward other = (UserSignAward) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIsInvested() == null ? other.getIsInvested() == null : this.getIsInvested().equals(other.getIsInvested()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getPrizeType() == null ? other.getPrizeType() == null : this.getPrizeType().equals(other.getPrizeType()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getRule() == null ? other.getRule() == null : this.getRule().equals(other.getRule()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign_award
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIsInvested() == null) ? 0 : getIsInvested().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getPrizeType() == null) ? 0 : getPrizeType().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getRule() == null) ? 0 : getRule().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign_award
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isInvested=").append(isInvested);
        sb.append(", userId=").append(userId);
        sb.append(", prizeType=").append(prizeType);
        sb.append(", count=").append(count);
        sb.append(", amount=").append(amount);
        sb.append(", rule=").append(rule);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}