package com.goochou.p2b.model.goods;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GoodsOrderInvestRelationExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	protected int limitStart = -1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	protected int limitEnd = -1;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public GoodsOrderInvestRelationExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public void setLimitStart(int limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public int getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTableTypeIsNull() {
			addCriterion("table_type is null");
			return (Criteria) this;
		}

		public Criteria andTableTypeIsNotNull() {
			addCriterion("table_type is not null");
			return (Criteria) this;
		}

		public Criteria andTableTypeEqualTo(Integer value) {
			addCriterion("table_type =", value, "tableType");
			return (Criteria) this;
		}

		public Criteria andTableTypeNotEqualTo(Integer value) {
			addCriterion("table_type <>", value, "tableType");
			return (Criteria) this;
		}

		public Criteria andTableTypeGreaterThan(Integer value) {
			addCriterion("table_type >", value, "tableType");
			return (Criteria) this;
		}

		public Criteria andTableTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("table_type >=", value, "tableType");
			return (Criteria) this;
		}

		public Criteria andTableTypeLessThan(Integer value) {
			addCriterion("table_type <", value, "tableType");
			return (Criteria) this;
		}

		public Criteria andTableTypeLessThanOrEqualTo(Integer value) {
			addCriterion("table_type <=", value, "tableType");
			return (Criteria) this;
		}

		public Criteria andTableTypeIn(List<Integer> values) {
			addCriterion("table_type in", values, "tableType");
			return (Criteria) this;
		}

		public Criteria andTableTypeNotIn(List<Integer> values) {
			addCriterion("table_type not in", values, "tableType");
			return (Criteria) this;
		}

		public Criteria andTableTypeBetween(Integer value1, Integer value2) {
			addCriterion("table_type between", value1, value2, "tableType");
			return (Criteria) this;
		}

		public Criteria andTableTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("table_type not between", value1, value2, "tableType");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdIsNull() {
			addCriterion("goods_order_id is null");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdIsNotNull() {
			addCriterion("goods_order_id is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdEqualTo(Integer value) {
			addCriterion("goods_order_id =", value, "goodsOrderId");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdNotEqualTo(Integer value) {
			addCriterion("goods_order_id <>", value, "goodsOrderId");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdGreaterThan(Integer value) {
			addCriterion("goods_order_id >", value, "goodsOrderId");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("goods_order_id >=", value, "goodsOrderId");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdLessThan(Integer value) {
			addCriterion("goods_order_id <", value, "goodsOrderId");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdLessThanOrEqualTo(Integer value) {
			addCriterion("goods_order_id <=", value, "goodsOrderId");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdIn(List<Integer> values) {
			addCriterion("goods_order_id in", values, "goodsOrderId");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdNotIn(List<Integer> values) {
			addCriterion("goods_order_id not in", values, "goodsOrderId");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdBetween(Integer value1, Integer value2) {
			addCriterion("goods_order_id between", value1, value2, "goodsOrderId");
			return (Criteria) this;
		}

		public Criteria andGoodsOrderIdNotBetween(Integer value1, Integer value2) {
			addCriterion("goods_order_id not between", value1, value2, "goodsOrderId");
			return (Criteria) this;
		}

		public Criteria andInvestIdIsNull() {
			addCriterion("invest_id is null");
			return (Criteria) this;
		}

		public Criteria andInvestIdIsNotNull() {
			addCriterion("invest_id is not null");
			return (Criteria) this;
		}

		public Criteria andInvestIdEqualTo(Integer value) {
			addCriterion("invest_id =", value, "investId");
			return (Criteria) this;
		}

		public Criteria andInvestIdNotEqualTo(Integer value) {
			addCriterion("invest_id <>", value, "investId");
			return (Criteria) this;
		}

		public Criteria andInvestIdGreaterThan(Integer value) {
			addCriterion("invest_id >", value, "investId");
			return (Criteria) this;
		}

		public Criteria andInvestIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("invest_id >=", value, "investId");
			return (Criteria) this;
		}

		public Criteria andInvestIdLessThan(Integer value) {
			addCriterion("invest_id <", value, "investId");
			return (Criteria) this;
		}

		public Criteria andInvestIdLessThanOrEqualTo(Integer value) {
			addCriterion("invest_id <=", value, "investId");
			return (Criteria) this;
		}

		public Criteria andInvestIdIn(List<Integer> values) {
			addCriterion("invest_id in", values, "investId");
			return (Criteria) this;
		}

		public Criteria andInvestIdNotIn(List<Integer> values) {
			addCriterion("invest_id not in", values, "investId");
			return (Criteria) this;
		}

		public Criteria andInvestIdBetween(Integer value1, Integer value2) {
			addCriterion("invest_id between", value1, value2, "investId");
			return (Criteria) this;
		}

		public Criteria andInvestIdNotBetween(Integer value1, Integer value2) {
			addCriterion("invest_id not between", value1, value2, "investId");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(BigDecimal value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(BigDecimal value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(BigDecimal value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(BigDecimal value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<BigDecimal> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<BigDecimal> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("state is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("state is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(Integer value) {
			addCriterion("state =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(Integer value) {
			addCriterion("state <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(Integer value) {
			addCriterion("state >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("state >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(Integer value) {
			addCriterion("state <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(Integer value) {
			addCriterion("state <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<Integer> values) {
			addCriterion("state in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<Integer> values) {
			addCriterion("state not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(Integer value1, Integer value2) {
			addCriterion("state between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(Integer value1, Integer value2) {
			addCriterion("state not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_goods_order_invest_relation
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_goods_order_invest_relation
     *
     * @mbg.generated do_not_delete_during_merge Fri May 10 15:33:37 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}