package com.goochou.p2b.dao;

import com.goochou.p2b.model.ActivityFake;
import com.goochou.p2b.model.ActivityFakeExample;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface ActivityFakeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_fake
     *
     * @mbggenerated Mon Dec 04 17:01:00 CST 2017
     */
    int countByExample(ActivityFakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_fake
     *
     * @mbggenerated Mon Dec 04 17:01:00 CST 2017
     */
    int deleteByExample(ActivityFakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_fake
     *
     * @mbggenerated Mon Dec 04 17:01:00 CST 2017
     */
    int insert(ActivityFake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_fake
     *
     * @mbggenerated Mon Dec 04 17:01:00 CST 2017
     */
    int insertSelective(ActivityFake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_fake
     *
     * @mbggenerated Mon Dec 04 17:01:00 CST 2017
     */
    List<ActivityFake> selectByExample(ActivityFakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_fake
     *
     * @mbggenerated Mon Dec 04 17:01:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") ActivityFake record, @Param("example") ActivityFakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_fake
     *
     * @mbggenerated Mon Dec 04 17:01:00 CST 2017
     */
    int updateByExample(@Param("record") ActivityFake record, @Param("example") ActivityFakeExample example);

    /**
     * 查询测试用户的资产信息
     *
     * @param activityId 活动id
     * @param type 1总年化额 2日年化额
     * @param date
     * @return
     */
    List<Map<String, Object>> queryActivityFake(@Param("activityId") Integer activityId, @Param("type") Integer type, @Param("date") Date date);
}