package com.goochou.p2b.dao;

import com.goochou.p2b.model.AndroidTunnel;
import com.goochou.p2b.model.AndroidTunnelExample;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface AndroidTunnelMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table android_tunnel
     * 
     * @mbggenerated Wed Nov 11 15:31:45 CST 2015
     */
    int countByExample(AndroidTunnelExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table android_tunnel
     * 
     * @mbggenerated Wed Nov 11 15:31:45 CST 2015
     */
    int deleteByExample(AndroidTunnelExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table android_tunnel
     * 
     * @mbggenerated Wed Nov 11 15:31:45 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table android_tunnel
     * 
     * @mbggenerated Wed Nov 11 15:31:45 CST 2015
     */
    int insert(AndroidTunnel record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table android_tunnel
     * 
     * @mbggenerated Wed Nov 11 15:31:45 CST 2015
     */
    int insertSelective(AndroidTunnel record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table android_tunnel
     * 
     * @mbggenerated Wed Nov 11 15:31:45 CST 2015
     */
    List<AndroidTunnel> selectByExample(AndroidTunnelExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table android_tunnel
     * 
     * @mbggenerated Wed Nov 11 15:31:45 CST 2015
     */
    AndroidTunnel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table android_tunnel
     * 
     * @mbggenerated Wed Nov 11 15:31:45 CST 2015
     */
    int updateByExampleSelective(@Param("record") AndroidTunnel record, @Param("example") AndroidTunnelExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table android_tunnel
     * 
     * @mbggenerated Wed Nov 11 15:31:45 CST 2015
     */
    int updateByExample(@Param("record") AndroidTunnel record, @Param("example") AndroidTunnelExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table android_tunnel
     * 
     * @mbggenerated Wed Nov 11 15:31:45 CST 2015
     */
    int updateByPrimaryKeySelective(AndroidTunnel record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table android_tunnel
     * 
     * @mbggenerated Wed Nov 11 15:31:45 CST 2015
     */
    int updateByPrimaryKey(AndroidTunnel record);

    /**
     * 查询所有Android渠道引流记录
     * @return
     */
    public List<Map<String, Object>> selectAll();

    /**
     * 根据引流机构代码查询该机构引流记录
     * 
     * @param code
     * @return
     */
    public List<Map<String, Object>> selectByChannelCode(String code);

    /**
     * 根据引流机构代码查询该机构引流数量
     * 
     * @param code
     * @return
     */
    public List<Map<String, Object>> selectCountByChannelCode(String code);

    /**
     * 查询安卓渠道相关资金统计
     * @param map 
     * 
     * @return
     */
    public List<Map<String, Object>> queryAllPage(Map<String, Object> map);

    /**
     * 查询安卓渠道相关资金统计记录条数
     * 
     * @param map
     * @return
     */
    public Integer queryCount();

    /**
     * 查询汇总信息
     * @param map 
     * 
     * @return
     */
    public Map<String, Object> queryTotal(Map<String, Object> map);

    /**
     * 根据安卓渠道代码查询用户综合信息列表
     * 
     * @param map
     * @return
     */
    public List<Map<String, Object>> queryAllAndroidDetailListByCode(Map<String, Object> map);

    /**
     * 安卓渠道代码对应其所属人员综合信息数量
     * 
     * @param map
     * @return
     */
    public Integer queryCountAllAndroidDetailListByCode(Map<String, Object> map);

    public List<Map<String, Object>> queryAllAndroidDetailListByCodePage(Map<String, Object> map);

    /**
     * 根据用户的角色分配的code查询其安卓渠道统计内容 刘源 2015-11-11
     * 
     * @param map
     * @return
     */
    public List<Map<String, Object>> queryCountByUserRole(Map<String, Object> map);
    
    /**
     * 根据用户的角色分配的code查询其安卓渠道每日详情统计内容 刘源 2015-11-16
     * 
     * @param map
     * @return
     */
    public List<Map<String, Object>> queryDailyCountByUserRole(Map<String, Object> map);

    /**
     * 查询用户是否在安卓渠道代码配置中
     * 
     * @param id
     *            >1 存在
     * @return
     */
    public int queryIsInAndroidTrunnelManagement(Integer id);

    /**
     * 根据用户的角色分配的code查询其安卓渠道每日详情统计内容记录总数量 刘源 2015-11-16
     * 
     * @param map
     * @return
     */
	public Integer queryAllDailyCountByUserRole(Map<String, Object> map);

    public List<Map<String, Object>> queryAndroidTrunnelManagement(Map<String, Object> map);

    public AndroidTunnel queryByImei(Map<String, Object> map);

    public String queryImeiByUserId(Integer userId);

}