package com.goochou.p2b.dao;

import com.goochou.p2b.model.goods.GoodsOrderRefund;
import com.goochou.p2b.model.goods.GoodsOrderRefundExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface GoodsOrderRefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order_refund
     *
     * @mbg.generated Tue Jun 04 15:51:19 CST 2019
     */
    long countByExample(GoodsOrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order_refund
     *
     * @mbg.generated Tue Jun 04 15:51:19 CST 2019
     */
    int deleteByExample(GoodsOrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order_refund
     *
     * @mbg.generated Tue Jun 04 15:51:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order_refund
     *
     * @mbg.generated Tue Jun 04 15:51:19 CST 2019
     */
    int insert(GoodsOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order_refund
     *
     * @mbg.generated Tue Jun 04 15:51:19 CST 2019
     */
    int insertSelective(GoodsOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order_refund
     *
     * @mbg.generated Tue Jun 04 15:51:19 CST 2019
     */
    List<GoodsOrderRefund> selectByExample(GoodsOrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order_refund
     *
     * @mbg.generated Tue Jun 04 15:51:19 CST 2019
     */
    GoodsOrderRefund selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order_refund
     *
     * @mbg.generated Tue Jun 04 15:51:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") GoodsOrderRefund record, @Param("example") GoodsOrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order_refund
     *
     * @mbg.generated Tue Jun 04 15:51:19 CST 2019
     */
    int updateByExample(@Param("record") GoodsOrderRefund record, @Param("example") GoodsOrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order_refund
     *
     * @mbg.generated Tue Jun 04 15:51:19 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order_refund
     *
     * @mbg.generated Tue Jun 04 15:51:19 CST 2019
     */
    int updateByPrimaryKey(GoodsOrderRefund record);

    /**
     * 退款审核列表
     * @author sxy
     * @param map
     * @return
     */
    List<Map<String, Object>> listGoodsOrderRefund(Map<String, Object> map);

    /**
     * 退款申请数量
     * @author sxy
     * @param map
     * @return
     */
    Integer countGoodsOrderRefund(Map<String, Object> map);

    /**
     * @description 锁记录
     * @author shuys
     * @date 2019/6/6
     * @param id
     * @return com.goochou.p2b.model.goods.GoodsOrderRefund
    */
    GoodsOrderRefund selectByPrimaryKeyForUpdate(Integer id);

}
