package com.goochou.p2b.dao;

import com.goochou.p2b.model.HongbaoRedeemLink;
import com.goochou.p2b.model.HongbaoRedeemLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HongbaoRedeemLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongbao_redeem_link
     *
     * @mbggenerated Wed Jun 29 17:17:57 CST 2016
     */
    int countByExample(HongbaoRedeemLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongbao_redeem_link
     *
     * @mbggenerated Wed Jun 29 17:17:57 CST 2016
     */
    int deleteByExample(HongbaoRedeemLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongbao_redeem_link
     *
     * @mbggenerated Wed Jun 29 17:17:57 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongbao_redeem_link
     *
     * @mbggenerated Wed Jun 29 17:17:57 CST 2016
     */
    int insert(HongbaoRedeemLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongbao_redeem_link
     *
     * @mbggenerated Wed Jun 29 17:17:57 CST 2016
     */
    int insertSelective(HongbaoRedeemLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongbao_redeem_link
     *
     * @mbggenerated Wed Jun 29 17:17:57 CST 2016
     */
    List<HongbaoRedeemLink> selectByExample(HongbaoRedeemLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongbao_redeem_link
     *
     * @mbggenerated Wed Jun 29 17:17:57 CST 2016
     */
    HongbaoRedeemLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongbao_redeem_link
     *
     * @mbggenerated Wed Jun 29 17:17:57 CST 2016
     */
    int updateByExampleSelective(@Param("record") HongbaoRedeemLink record, @Param("example") HongbaoRedeemLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongbao_redeem_link
     *
     * @mbggenerated Wed Jun 29 17:17:57 CST 2016
     */
    int updateByExample(@Param("record") HongbaoRedeemLink record, @Param("example") HongbaoRedeemLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongbao_redeem_link
     *
     * @mbggenerated Wed Jun 29 17:17:57 CST 2016
     */
    int updateByPrimaryKeySelective(HongbaoRedeemLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongbao_redeem_link
     *
     * @mbggenerated Wed Jun 29 17:17:57 CST 2016
     */
    int updateByPrimaryKey(HongbaoRedeemLink record);

    /**
     * @Description(描述):根据兑换码ID 查询整套对应的兑换码模版ID
     * @author 王信
     * @date 2016/6/30
     * @params
     **/
    List<HongbaoRedeemLink> queryById(@Param("redeemId")Integer redeemId);
}