package com.goochou.p2b.dao;

import com.goochou.p2b.model.HongbaoTemplate;
import com.goochou.p2b.model.HongbaoTemplateExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HongbaoTemplateMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hongbao_template
     * @mbg.generated  Tue Jun 18 17:06:59 CST 2019
     */
    long countByExample(HongbaoTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hongbao_template
     * @mbg.generated  Tue Jun 18 17:06:59 CST 2019
     */
    int deleteByExample(HongbaoTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hongbao_template
     * @mbg.generated  Tue Jun 18 17:06:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hongbao_template
     * @mbg.generated  Tue Jun 18 17:06:59 CST 2019
     */
    int insert(HongbaoTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hongbao_template
     * @mbg.generated  Tue Jun 18 17:06:59 CST 2019
     */
    int insertSelective(HongbaoTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hongbao_template
     * @mbg.generated  Tue Jun 18 17:06:59 CST 2019
     */
    List<HongbaoTemplate> selectByExample(HongbaoTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hongbao_template
     * @mbg.generated  Tue Jun 18 17:06:59 CST 2019
     */
    HongbaoTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hongbao_template
     * @mbg.generated  Tue Jun 18 17:06:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") HongbaoTemplate record,
        @Param("example") HongbaoTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hongbao_template
     * @mbg.generated  Tue Jun 18 17:06:59 CST 2019
     */
    int updateByExample(@Param("record") HongbaoTemplate record, @Param("example") HongbaoTemplateExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hongbao_template
     * @mbg.generated  Tue Jun 18 17:06:59 CST 2019
     */
    int updateByPrimaryKeySelective(HongbaoTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table hongbao_template
     * @mbg.generated  Tue Jun 18 17:06:59 CST 2019
     */
    int updateByPrimaryKey(HongbaoTemplate record);

    List<Map<String,Object>> query(Map<String, Object> map);

    Integer queryCount(Map<String, Object> map);

    /**
     * 查询红包模板信息
     * @param id
     * @author 刘源
     * @date 2016/6/24
     */
    Map<String,Object> queryById(@Param("id")Integer id);

    /**
     * 查询兑换码对应的红包信息
     * @param redeemId
     * @author 刘源
     * @date 2016/7/7
     */
    List<HongbaoTemplate> queryByRedeemId(@Param("redeemId") Integer redeemId);
}