package com.goochou.p2b.dao;

import com.goochou.p2b.model.Interest;
import com.goochou.p2b.model.InterestProduct;
import com.goochou.p2b.model.InterestProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InterestProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_product
     *
     * @mbggenerated Fri Mar 17 18:31:28 CST 2017
     */
    int countByExample(InterestProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_product
     *
     * @mbggenerated Fri Mar 17 18:31:28 CST 2017
     */
    int deleteByExample(InterestProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_product
     *
     * @mbggenerated Fri Mar 17 18:31:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_product
     *
     * @mbggenerated Fri Mar 17 18:31:28 CST 2017
     */
    int insert(InterestProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_product
     *
     * @mbggenerated Fri Mar 17 18:31:28 CST 2017
     */
    int insertSelective(InterestProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_product
     *
     * @mbggenerated Fri Mar 17 18:31:28 CST 2017
     */
    List<InterestProduct> selectByExample(InterestProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_product
     *
     * @mbggenerated Fri Mar 17 18:31:28 CST 2017
     */
    InterestProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_product
     *
     * @mbggenerated Fri Mar 17 18:31:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") InterestProduct record, @Param("example") InterestProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_product
     *
     * @mbggenerated Fri Mar 17 18:31:28 CST 2017
     */
    int updateByExample(@Param("record") InterestProduct record, @Param("example") InterestProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_product
     *
     * @mbggenerated Fri Mar 17 18:31:28 CST 2017
     */
    int updateByPrimaryKeySelective(InterestProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interest_product
     *
     * @mbggenerated Fri Mar 17 18:31:28 CST 2017
     */
    int updateByPrimaryKey(InterestProduct record);
    public InterestProduct getYestodayInterest(Integer investmentId);
}