package com.goochou.p2b.dao;

import com.goochou.p2b.model.InvestmentView;
import com.goochou.p2b.model.InvestmentViewExample;
import java.util.List;
import java.util.Map;

import com.goochou.p2b.model.vo.InvestmentOrderVO;
import org.apache.ibatis.annotations.Param;

public interface InvestmentViewMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investment_view
	 * @mbg.generated
	 */
	long countByExample(InvestmentViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investment_view
	 * @mbg.generated
	 */
	List<InvestmentView> selectByExample(InvestmentViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investment_view
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") InvestmentView record,
			@Param("example") InvestmentViewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table investment_view
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") InvestmentView record, @Param("example") InvestmentViewExample example);

	double sumAmountByExample(InvestmentViewExample example);

    long countUserByExample(InvestmentViewExample example);

    List<InvestmentOrderVO> listInvestmentVoByExampleAndCondition(@Param("params")Map<String, Object> map, @Param("example")InvestmentViewExample example);

    long countInvestmentVoByExampleAndCondition(@Param("params")Map<String, Object> map,@Param("example")InvestmentViewExample example);

    Map sumInvestmentVoByExampleAndCondition(@Param("params")Map<String, Object> map, @Param("example")InvestmentViewExample example);
}
