package com.goochou.p2b.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.goochou.p2b.model.InviteUserAcitvityAwardLog;
import com.goochou.p2b.model.InviteUserAcitvityAwardLogExample;

public interface InviteUserAcitvityAwardLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_user_acitvity_award_log
     *
     * @mbggenerated Mon Apr 23 19:35:51 CST 2018
     */
    int countByExample(InviteUserAcitvityAwardLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_user_acitvity_award_log
     *
     * @mbggenerated Mon Apr 23 19:35:51 CST 2018
     */
    int deleteByExample(InviteUserAcitvityAwardLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_user_acitvity_award_log
     *
     * @mbggenerated Mon Apr 23 19:35:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_user_acitvity_award_log
     *
     * @mbggenerated Mon Apr 23 19:35:51 CST 2018
     */
    int insert(InviteUserAcitvityAwardLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_user_acitvity_award_log
     *
     * @mbggenerated Mon Apr 23 19:35:51 CST 2018
     */
    int insertSelective(InviteUserAcitvityAwardLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_user_acitvity_award_log
     *
     * @mbggenerated Mon Apr 23 19:35:51 CST 2018
     */
    List<InviteUserAcitvityAwardLog> selectByExample(InviteUserAcitvityAwardLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_user_acitvity_award_log
     *
     * @mbggenerated Mon Apr 23 19:35:51 CST 2018
     */
    InviteUserAcitvityAwardLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_user_acitvity_award_log
     *
     * @mbggenerated Mon Apr 23 19:35:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") InviteUserAcitvityAwardLog record, @Param("example") InviteUserAcitvityAwardLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_user_acitvity_award_log
     *
     * @mbggenerated Mon Apr 23 19:35:51 CST 2018
     */
    int updateByExample(@Param("record") InviteUserAcitvityAwardLog record, @Param("example") InviteUserAcitvityAwardLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_user_acitvity_award_log
     *
     * @mbggenerated Mon Apr 23 19:35:51 CST 2018
     */
    int updateByPrimaryKeySelective(InviteUserAcitvityAwardLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_user_acitvity_award_log
     *
     * @mbggenerated Mon Apr 23 19:35:51 CST 2018
     */
    int updateByPrimaryKey(InviteUserAcitvityAwardLog record);

    List<Map<String, Object>> getInviteUserActivity(Map<String, Object> map);
    
    /***
     * 获取我的收益列表
     * @param map
     * @return
     */
    List<Map<String, Object>> getMyInviteInComePageList(Map<String, Object> map);
}