package com.goochou.p2b.dao;

import com.goochou.p2b.model.MallActivity;
import com.goochou.p2b.model.MallActivityExample;
import java.util.List;

import com.goochou.p2b.model.vo.bulls.MallActivityVO;
import org.apache.ibatis.annotations.Param;

public interface MallActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity
     *
     * @mbg.generated
     */
    long countByExample(MallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity
     *
     * @mbg.generated
     */
    int deleteByExample(MallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity
     *
     * @mbg.generated
     */
    int insert(MallActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity
     *
     * @mbg.generated
     */
    int insertSelective(MallActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity
     *
     * @mbg.generated
     */
    List<MallActivity> selectByExample(MallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity
     *
     * @mbg.generated
     */
    MallActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallActivity record, @Param("example") MallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallActivity record, @Param("example") MallActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallActivity record);
    
    //  ************************************************************************************************ 

    MallActivity selectByPrimaryKeyForUpdate(Integer id);
    
    List<MallActivityVO> listMallActivity(MallActivityExample example);

    long countMallActivity(MallActivityExample example);
}
