package com.goochou.p2b.dao;

import com.goochou.p2b.model.MallActivitySecondKill;
import com.goochou.p2b.model.MallActivitySecondKillExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.goochou.p2b.model.vo.bulls.MallActivitySecondKillVO;
import com.goochou.p2b.model.vo.bulls.SecondKillDetailVO;
import org.apache.ibatis.annotations.Param;

public interface MallActivitySecondKillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    long countByExample(MallActivitySecondKillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    int deleteByExample(MallActivitySecondKillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    int insert(MallActivitySecondKill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    int insertSelective(MallActivitySecondKill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    List<MallActivitySecondKill> selectByExample(MallActivitySecondKillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    MallActivitySecondKill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallActivitySecondKill record, @Param("example") MallActivitySecondKillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallActivitySecondKill record, @Param("example") MallActivitySecondKillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallActivitySecondKill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mall_activity_second_kill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallActivitySecondKill record);
    
    // *****************************************************************************************************************

    MallActivitySecondKill selectByPrimaryKeyForUpdate(Integer id);
    
    List<MallActivitySecondKillVO> listMallActivitySecondKill(Map<String, Object> params);

    int countMallActivitySecondKill(Map<String, Object> params);

    /**
     * 获取当天的秒杀商品配置数据
     * @param currDate 当前服务器的时间点
     * @param detailId 活动详情编号
     * @return
     */
    List<SecondKillDetailVO> getTheSameDaySecondKillDetails(@Param("currDate") Date currDate, @Param("detailId") Integer detailId);

    /**
     * 根据秒杀商品记录id获取该商品的销售量
     * @param activitySecondKillId
     * @return int
    */
    int getSaledCountByActivitySecondKillId(Integer activitySecondKillId);
}
