package com.goochou.p2b.dao;

import com.goochou.p2b.model.Message;
import com.goochou.p2b.model.MessageExample;
import com.goochou.p2b.model.MessageReceiver;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message
     *
     * @mbggenerated Sat Aug 29 13:49:39 CST 2015
     */
    int countByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message
     *
     * @mbggenerated Sat Aug 29 13:49:39 CST 2015
     */
    int deleteByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message
     *
     * @mbggenerated Sat Aug 29 13:49:39 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message
     *
     * @mbggenerated Sat Aug 29 13:49:39 CST 2015
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message
     *
     * @mbggenerated Sat Aug 29 13:49:39 CST 2015
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message
     *
     * @mbggenerated Sat Aug 29 13:49:39 CST 2015
     */
    List<Message> selectByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message
     *
     * @mbggenerated Sat Aug 29 13:49:39 CST 2015
     */
    Message selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message
     *
     * @mbggenerated Sat Aug 29 13:49:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message
     *
     * @mbggenerated Sat Aug 29 13:49:39 CST 2015
     */
    int updateByExample(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message
     *
     * @mbggenerated Sat Aug 29 13:49:39 CST 2015
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table message
     *
     * @mbggenerated Sat Aug 29 13:49:39 CST 2015
     */
    int updateByPrimaryKey(Message record);

    /**
     * 根据ID删除消息以及其级联字表的消息接收信息表
     *
     * @param id
     */
    public void deleteByMessageId(Integer id);

    public List<Map<String, Object>> list(@Param("keyword") String keyword, @Param("start") Integer start, @Param("limit") Integer limit);

    public Integer listCount(@Param("keyword") String keyword);

    void insertBatch(List<MessageReceiver> list);

}