package com.goochou.p2b.dao;

import com.goochou.p2b.model.ProjectLifePicture;
import com.goochou.p2b.model.ProjectLifePictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectLifePictureMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table project_life_picture
     * @mbg.generated
     */
    long countByExample(ProjectLifePictureExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table project_life_picture
     * @mbg.generated
     */
    int deleteByExample(ProjectLifePictureExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table project_life_picture
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table project_life_picture
     * @mbg.generated
     */
    int insert(ProjectLifePicture record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table project_life_picture
     * @mbg.generated
     */
    int insertSelective(ProjectLifePicture record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table project_life_picture
     * @mbg.generated
     */
    List<ProjectLifePicture> selectByExample(ProjectLifePictureExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table project_life_picture
     * @mbg.generated
     */
    ProjectLifePicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table project_life_picture
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProjectLifePicture record,
        @Param("example") ProjectLifePictureExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table project_life_picture
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProjectLifePicture record,
        @Param("example") ProjectLifePictureExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table project_life_picture
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectLifePicture record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table project_life_picture
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectLifePicture record);
}