package com.goochou.p2b.dao;

import com.goochou.p2b.model.ProjectCreditor;
import com.goochou.p2b.model.ProjectCreditorExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ProjectCreditorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_creditor
     *
     * @mbggenerated Wed Mar 09 10:53:05 CST 2016
     */
    int countByExample(ProjectCreditorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_creditor
     *
     * @mbggenerated Wed Mar 09 10:53:05 CST 2016
     */
    int deleteByExample(ProjectCreditorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_creditor
     *
     * @mbggenerated Wed Mar 09 10:53:05 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_creditor
     *
     * @mbggenerated Wed Mar 09 10:53:05 CST 2016
     */
    int insert(ProjectCreditor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_creditor
     *
     * @mbggenerated Wed Mar 09 10:53:05 CST 2016
     */
    int insertSelective(ProjectCreditor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_creditor
     *
     * @mbggenerated Wed Mar 09 10:53:05 CST 2016
     */
    List<ProjectCreditor> selectByExample(ProjectCreditorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_creditor
     *
     * @mbggenerated Wed Mar 09 10:53:05 CST 2016
     */
    ProjectCreditor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_creditor
     *
     * @mbggenerated Wed Mar 09 10:53:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProjectCreditor record, @Param("example") ProjectCreditorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_creditor
     *
     * @mbggenerated Wed Mar 09 10:53:05 CST 2016
     */
    int updateByExample(@Param("record") ProjectCreditor record, @Param("example") ProjectCreditorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_creditor
     *
     * @mbggenerated Wed Mar 09 10:53:05 CST 2016
     */
    int updateByPrimaryKeySelective(ProjectCreditor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_creditor
     *
     * @mbggenerated Wed Mar 09 10:53:05 CST 2016
     */
    int updateByPrimaryKey(ProjectCreditor record);
    
    /**
     * 查询债权列表
    * @author 刘源
    * @date 2016年2月16日
    * @parameter  
    * @return
     */
	public List<Map<String, Object>> queryAllCreditorList(Map<String, Object> map);

	/**
	 * 查询债权列表总数
	* @author 刘源
	* @date 2016年2月16日
	* @parameter  
	* @return
	 */
	public Integer queryAllCreditorListCount(Map<String, Object> map);

	/**
	 * 查询债权详情：个人用户入口
	* @author 刘源
	* @date 2016年2月16日
	* @parameter  
	* @return
	 */
	public Map<String, Object> queryCreditorDetail(Map<String, Object> map);

	/**
	 * 债权详情: 项目列表入口
	 * @author 刘源
	 * @date 2016年2月26日
	 * @parameter  
	 * @return
	 */
	public Map<String, Object> queryProjectCreditorDetail(Map<String, Object> map);

	/**
	 * 判断项目是否已经配置债权
	 * @author 刘源
	 * @date 2016年3月9日
	 * @parameter  
	 * @return
	 */
	public Boolean checkProjectHasCreditor(@Param(value = "projectId")Integer projectId);

	/**
	 * 查询项目债权配置信息
	 * @author 刘源
	 * @date 2016年3月9日
	 * @parameter  
	 * @return
	 */
	public Map<String, Object> queryProjectCreditorConfig(Integer id);

	/**
	 * 删除债权模板内容检测
	 * @author 刘源
	 * @date 2016年3月9日
	 * @parameter  
	 * @return
	 */
	public Boolean checkContractDelete(@Param(value = "detailId")Integer detailId);

	/**
	 * 查询项目配置的债权
	 * @author 刘源
	 * @date 2016年3月16日
	 * @parameter  
	 * @return
	 */
	public ProjectCreditor queryCreditorDeailByProjectId(Map<String, Object> map);

	/**
	 * @Description: 根据项目id  查询配置债权的详细信息
	 * @date  2016/11/8
	 * @author 王信
	 */
	public Map<String,Object> queryProjectConfig(Integer id);
	
	/**
	 * 新债权转让列表查询
	 * @param map
	 * @return
	 */
	public List<Map<String, Object>> queryNewAllCreditorList(Map<String, Object> map);
	
	/**
	 * 新债权转让列表查询
	 * @param map
	 * @return
	 */
	public Integer queryNewAllCreditorListCount(Map<String, Object> map);
}