package com.goochou.p2b.dao;

import com.goochou.p2b.model.RechargeOfflineApply;
import com.goochou.p2b.model.RechargeOfflineApplyExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface RechargeOfflineApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_offline_apply
     *
     * @mbggenerated
     */
    int countByExample(RechargeOfflineApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_offline_apply
     *
     * @mbggenerated
     */
    int deleteByExample(RechargeOfflineApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_offline_apply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_offline_apply
     *
     * @mbggenerated
     */
    int insert(RechargeOfflineApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_offline_apply
     *
     * @mbggenerated
     */
    int insertSelective(RechargeOfflineApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_offline_apply
     *
     * @mbggenerated
     */
    List<RechargeOfflineApply> selectByExample(RechargeOfflineApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_offline_apply
     *
     * @mbggenerated
     */
    RechargeOfflineApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_offline_apply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RechargeOfflineApply record, @Param("example") RechargeOfflineApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_offline_apply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RechargeOfflineApply record, @Param("example") RechargeOfflineApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_offline_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RechargeOfflineApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_offline_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RechargeOfflineApply record);
    
    List<Map<String,Object>> selectByExampleAndCondition(@Param("example")RechargeOfflineApplyExample example
    		,@Param("adminId")Integer adminId ,@Param("onlySelfApply")Boolean onlySelfApply,@Param("keyword")String keyword);
    
    
    Long countByExampleAndCondition(@Param("example")RechargeOfflineApplyExample example
    		,@Param("adminId")Integer adminId ,@Param("onlySelfApply")Boolean onlySelfApply,@Param("keyword")String keyword);
    
    
    
    Map<String, Object> queryById(Integer id);
    
}
