package com.goochou.p2b.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.goochou.p2b.model.SecurityProblem;
import com.goochou.p2b.model.SecurityProblemExample;

public interface SecurityProblemMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table security_problem
     * 
     * @mbggenerated Thu Dec 18 14:02:13 CST 2014
     */
    int countByExample(SecurityProblemExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table security_problem
     * 
     * @mbggenerated Thu Dec 18 14:02:13 CST 2014
     */
    int deleteByExample(SecurityProblemExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table security_problem
     * 
     * @mbggenerated Thu Dec 18 14:02:13 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table security_problem
     * 
     * @mbggenerated Thu Dec 18 14:02:13 CST 2014
     */
    int insert(SecurityProblem record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table security_problem
     * 
     * @mbggenerated Thu Dec 18 14:02:13 CST 2014
     */
    int insertSelective(SecurityProblem record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table security_problem
     * 
     * @mbggenerated Thu Dec 18 14:02:13 CST 2014
     */
    List<SecurityProblem> selectByExample(SecurityProblemExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table security_problem
     * 
     * @mbggenerated Thu Dec 18 14:02:13 CST 2014
     */
    SecurityProblem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table security_problem
     * 
     * @mbggenerated Thu Dec 18 14:02:13 CST 2014
     */
    int updateByExampleSelective(@Param("record") SecurityProblem record, @Param("example") SecurityProblemExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table security_problem
     * 
     * @mbggenerated Thu Dec 18 14:02:13 CST 2014
     */
    int updateByExample(@Param("record") SecurityProblem record, @Param("example") SecurityProblemExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table security_problem
     * 
     * @mbggenerated Thu Dec 18 14:02:13 CST 2014
     */
    int updateByPrimaryKeySelective(SecurityProblem record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table security_problem
     * 
     * @mbggenerated Thu Dec 18 14:02:13 CST 2014
     */
    int updateByPrimaryKey(SecurityProblem record);

    SecurityProblem getByUserId(int userId);
}