package com.goochou.p2b.dao;

import com.goochou.p2b.model.TunnelHeshiOrder;
import com.goochou.p2b.model.TunnelHeshiOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TunnelHeshiOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    int countByExample(TunnelHeshiOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    int deleteByExample(TunnelHeshiOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    int insert(TunnelHeshiOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    int insertSelective(TunnelHeshiOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    List<TunnelHeshiOrder> selectByExample(TunnelHeshiOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    TunnelHeshiOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") TunnelHeshiOrder record, @Param("example") TunnelHeshiOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    int updateByExample(@Param("record") TunnelHeshiOrder record, @Param("example") TunnelHeshiOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    int updateByPrimaryKeySelective(TunnelHeshiOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tunnel_heshi_order
     *
     * @mbggenerated Fri Jun 09 13:42:58 CST 2017
     */
    int updateByPrimaryKey(TunnelHeshiOrder record);
}