package com.goochou.p2b.dao;

import com.goochou.p2b.model.UserOperationRecord;
import com.goochou.p2b.model.UserOperationRecordExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface UserOperationRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_record
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int countByExample(UserOperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_record
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int deleteByExample(UserOperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_record
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_record
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int insert(UserOperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_record
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int insertSelective(UserOperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_record
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    List<UserOperationRecord> selectByExample(UserOperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_record
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    UserOperationRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_record
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserOperationRecord record, @Param("example") UserOperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_record
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int updateByExample(@Param("record") UserOperationRecord record, @Param("example") UserOperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_record
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int updateByPrimaryKeySelective(UserOperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_record
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int updateByPrimaryKey(UserOperationRecord record);


    /**
     * 查询用户绑卡记录
     * @param map
     * @author 刘源
     * @date 2016/5/24
     */
    List<Map<String,Object>> queryBindCardList(Map<String, Object> map);

    /**
     * 查询用户绑卡记录总数
     * @param map
     * @author 刘源
     * @date 2016/5/24
     */
    Integer queryBindCardListCount(Map<String, Object> map);

    /**
     *
     * @param id
     * @author 刘源
     * @date 2016/5/24
     */
    Map<String,Object> queryById(@Param("id") Integer id);

    /**
     * 判断解绑银行卡操作是否处于审核中
     * @param map
     * @author 刘源
     * @date 2016/5/30
     */
    Boolean queryApplyIsAudit(Map<String, Object> map);

    /**
     * 判断是否首次绑卡
     * @param userId
     * @author 刘源
     * @date 2016/6/14
     */
    Boolean queryIsFirstBind(@Param("userId") Integer userId);
}