package com.goochou.p2b.dao;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.goochou.p2b.model.AllAssetsExcel;
import com.goochou.p2b.model.Resources;
import com.goochou.p2b.model.UserAdmin;
import com.goochou.p2b.model.UserAdminExample;
import com.goochou.p2b.model.vo.CapitalDetail;

public interface UserAdminMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_admin
     * @mbg.generated
     */
    int countByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_admin
     * @mbg.generated
     */
    int deleteByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_admin
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_admin
     * @mbg.generated
     */
    int insert(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_admin
     * @mbg.generated
     */
    int insertSelective(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_admin
     * @mbg.generated
     */
    List<UserAdmin> selectByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_admin
     * @mbg.generated
     */
    UserAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_admin
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserAdmin record, @Param("example") UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_admin
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserAdmin record, @Param("example") UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_admin
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_admin
     * @mbg.generated
     */
    int updateByPrimaryKey(UserAdmin record);

    /**
     * 通过userAdminId去查询这个管理员拥有的所有权限
     *
     * @param userAdminId
     * @return List<Resources>
     * @Author:xinjiang
     */
    List<Resources> selectResourcesByAdminId(@Param("userAdminId") Integer userAdminId, @Param("isMenu") Integer isMenu,
	    @Param("parentId") Integer parentId, @Param("isOrder") boolean isOrder);

    public String getRoleNameByUserId(Integer userId);

    public List<Map<String, Object>> getAllUserAssets(Map<String, Object> map);

    public Integer getAllUserAssetsCount();

    public List<AllAssetsExcel> getAllUserAssetsExcel(Map<String, Object> map);

    public List<CapitalDetail> getAllCapitalDetail(Map<String, Object> map);

    public List<Map<String, Object>> getAllCapitalDetailForPage(Map<String, Object> map);

    public Integer getCapitalDetailCount();

    public abstract List<CapitalDetail> getAllCapitalDetailForMonth(Date month);

    Map<String, Object> getSummarizingForMonth(@Param("month") Date month, @Param("source") Integer source);

    /**
     * 根据权限查询admin用户
     * 
     * @author xueqi
     * @param map
     * @return List<UserAdmin>
     */
    public List<UserAdmin> queryUserAdminByRoleId(Map<String, Object> map);

    List<UserAdmin> queryUserAdminByCustomerUserId(Map<String, Object> map);

    Integer queryUserAdminByPhone(String mobilePhone);

    List<UserAdmin> selectUserAdminList(Map<String, Object> map);

    int countUserAdminList(Map<String, Object> map);
}