package com.goochou.p2b.dao;

import com.goochou.p2b.model.UserAuthentication;
import com.goochou.p2b.model.UserAuthenticationExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface UserAuthenticationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int countByExample(UserAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int deleteByExample(UserAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int insert(UserAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int insertSelective(UserAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    List<UserAuthentication> selectByExample(UserAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    UserAuthentication selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserAuthentication record, @Param("example") UserAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int updateByExample(@Param("record") UserAuthentication record, @Param("example") UserAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int updateByPrimaryKeySelective(UserAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication
     *
     * @mbggenerated Wed Jun 22 16:42:51 CST 2016
     */
    int updateByPrimaryKey(UserAuthentication record);

    /**
     * 查询用户实名记录
     * @param map
     * @author 刘源
     * @date 2016/5/24
     */
    List<Map<String,Object>> queryAuthenticationList(Map<String, Object> map);

    /**
     * 查询用户实名记录总数
     * @param map
     * @author 刘源
     * @date 2016/5/24
     */
    Integer queryAuthenticationListCount(Map<String, Object> map);

    /**
     * 查询用户实名操作记录
     * @param id
     * @author 刘源
     * @date 2016/5/24
     */
    Map<String,Object> queryByIdWithMap(@Param("id") Integer id);

    /**
     * 判断解除实名认证操作是否处于审核中
     * @param map
     * @author 刘源
     * @date 2016/5/30
     */
    Boolean queryApplyIsAudit(Map<String, Object> map);
    
    
    Boolean queryAuthByUserInfo(@Param("userId")Integer userId, @Param("realName")String realName, @Param("idCard")String idCard);
}