package com.goochou.p2b.dao;

import com.goochou.p2b.model.ExportWxActivity;
import com.goochou.p2b.model.WxActivity;
import com.goochou.p2b.model.WxActivityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface WxActivityMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wx_activity
     *
     * @mbggenerated Tue Oct 27 10:26:04 CST 2015
     */
    int countByExample(WxActivityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wx_activity
     *
     * @mbggenerated Tue Oct 27 10:26:04 CST 2015
     */
    int deleteByExample(WxActivityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wx_activity
     *
     * @mbggenerated Tue Oct 27 10:26:04 CST 2015
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wx_activity
     *
     * @mbggenerated Tue Oct 27 10:26:04 CST 2015
     */
    int insert(WxActivity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wx_activity
     *
     * @mbggenerated Tue Oct 27 10:26:04 CST 2015
     */
    int insertSelective(WxActivity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wx_activity
     *
     * @mbggenerated Tue Oct 27 10:26:04 CST 2015
     */
    List<WxActivity> selectByExample(WxActivityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wx_activity
     *
     * @mbggenerated Tue Oct 27 10:26:04 CST 2015
     */
    WxActivity selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wx_activity
     *
     * @mbggenerated Tue Oct 27 10:26:04 CST 2015
     */
    int updateByExampleSelective(@Param("record") WxActivity record, @Param("example") WxActivityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wx_activity
     *
     * @mbggenerated Tue Oct 27 10:26:04 CST 2015
     */
    int updateByExample(@Param("record") WxActivity record, @Param("example") WxActivityExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wx_activity
     *
     * @mbggenerated Tue Oct 27 10:26:04 CST 2015
     */
    int updateByPrimaryKeySelective(WxActivity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wx_activity
     *
     * @mbggenerated Tue Oct 27 10:26:04 CST 2015
     */
    int updateByPrimaryKey(WxActivity record);

    public  List<Map<String, Object>> list();

    public  List<Map<String, Object>> report(Map<String, Object> paramMap);

    public  List<Map<String, Object>> detail2(Map<String, Object> paramMap);

    public  List<ExportWxActivity> detail(Map<String, Object> paramMap);

    public  Integer reportCount(Map<String, Object> paramMap);

    public  Integer detailCount(Map<String, Object> paramMap);

    public  Integer detailCount2(Map<String, Object> paramMap);

    public  Double sumAmount(Map<String, Object> paramMap);

    public  List<Map<String, Object>> processZcAndSm(Map<String, Object> paramMap);

    public  List<Map<String, Object>> processBindCard(Map<String, Object> paramMap);

    public  List<Map<String, Object>> processInv(Map<String, Object> paramMap);

    public  List<Map<String, Object>> dataAnalysis(Map<String, Object> paramMap);
    public  Integer countDataAnalysis(Map<String, Object> paramMap);

    /**
     *  渠道数据统计（注册人手机号，是否实名，是否绑卡，投资总额【包括新手标，不包括债权转让】）
     * @author
     * @date 2016年11月2日
     * @parameter
     * @return
     */
    public List<Map<String, Object>> processCommon(Map<String, Object> paramMap);


    /**
     *微信推广首次投资
     * @return
     * @author zxx
     * @date 2016年11月26日
     * @parameter
     */
    public List<Map<String, Object>> detail3(Map<String, Object> paramMap);
    public Integer detailCount3(Map<String, Object> paramMap);

    /**
     *微信推广在投情况
     * @return
     * @author zxx
     * @date 2016年11月26日
     * @parameter
     */
    public List<Map<String, Object>> detail4(Map<String, Object> paramMap);
    public Integer detailCount4(Map<String, Object> paramMap);

    /**
     *微信推广复投情况
     * @return
     * @author zxx
     * @date 2016年11月27日
     * @parameter
     */
    public List<Map<String, Object>> detail5(Map<String, Object> paramMap);
    public Integer detailCount5(Map<String, Object> paramMap);



}